#!/bin/sh
# Copyright (c) 2012-2013 National Instruments.
# All rights reserved.

VPNCTL=/usr/sbin/vpnctl

VPN_LOAD_ON_STARTUP=yes

# The VERBOSE setting in /etc/default/rcS is deliberately ignored: the existence
# of a firewall or VPN configuration must always be logged to the console.

DEFAULTS=/etc/default/vpn
[ -f $DEFAULTS ] && . $DEFAULTS

if [ "$VPN_LOAD_ON_STARTUP" != "yes" ] ; then
	echo "Skipping VPN startup."
	exit 0
fi

[ -x $VPNCTL ] && $VPNCTL $@
