#!/bin/bash
set -e

# MODE determines the operation to be performed
# get or set
declare -r MODE="${1:-}"

NIRECOVERY_MOUNTPOINT=/mnt/NIRECOVERY

image_get () {
	if ! mount -o remount,rw $NIRECOVERY_MOUNTPOINT; then
		echo "Make sure the media is labeled NIRECOVERY and is writable" && false
	fi

	mkdir -p $NIRECOVERY_MOUNTPOINT/replication_images
	nisystemimage getall -x tgz -f $NIRECOVERY_MOUNTPOINT/replication_images/systemimage.tgz
	mount -o remount,ro $NIRECOVERY_MOUNTPOINT
	echo "Done getting image"
}

image_set () {
	if [[ $(type -t early_setup) != function ]]; then
		# If we're here, the script was invoked manually i.e., not from init.
		# So do the required setup.
		source /ni_provisioning.common
		early_setup
	fi

	source /ni_provisioning.safemode.common
	install_safemode

	nisystemimage setall -x tgz -f $NIRECOVERY_MOUNTPOINT/replication_images/systemimage.tgz -p reset -s reset

	# Retain some grubenv settings
	if grep --quiet "^consoleoutenable=" $BOOTFS_MOUNTPOINT/grub/grubenv; then
		grubenv_consoleoutenable=$(grub-editenv $BOOTFS_MOUNTPOINT/grub/grubenv list |grep "^consoleoutenable=" | cut -f 2 -d '=')
	fi
	if grep --quiet "^bootdelay=" $BOOTFS_MOUNTPOINT/grub/grubenv; then
		grubenv_bootdelay=$(grub-editenv $BOOTFS_MOUNTPOINT/grub/grubenv list |grep "^bootdelay=" | cut -f 2 -d '=')
	fi
	rm -rf mkdir $BOOTFS_MOUNTPOINT/grub

	install_grubenv
	set_versions

	echo $LOG_LEVEL > /proc/sys/kernel/printk
	sanity_check

	print_info "Re-enabling automount..."
	enable_automount
	print_done

	trap - ERR
	exec 1>&3
	exec 2>&4
}

image_${MODE}
