#! /bin/sh

DAEMON=/sbin/acpid
PIDFILE=/var/run/acpid.pid

test -x $DAEMON || exit 0
test -d /proc/acpi || exit 0

case "$1" in
  start)
    echo -n "Starting Advanced Configuration and Power Interface daemon: "
    start-stop-daemon -S -a $DAEMON -p $PIDFILE -n acpid -- -a /etc/acpid.conf -c /etc/acpi
    echo "acpid."
    ;;
  stop)
    echo -n "Stopping Advanced Configuration and Power Interface daemon: "
    start-stop-daemon -K -p $PIDFILE -n acpid --retry 5
    echo "acpid."
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/acpid {start|stop|restart|force-reload}"
    exit 1
esac

exit 0
