#!/bin/sh
#
# Copyright (c) 2013 National Instruments
#
### BEGIN INIT INFO
# Provides: crond
# Default-Start:  2345
# Default-Stop:   016
# Short-Description: run cron daemon
# Description: cron is a standard UNIX program that runs user-specified
#			  Cron scheduling daemon, as implemented by Busybox
### END INIT INFO

CROND=/usr/sbin/crond
ARGS="-c /etc/cron/crontabs"
NIRTCFG=/usr/local/natinst/bin/nirtcfg

[ -x $CROND ] || exit 1
[ -x $NIRTCFG ] || exit 1


# Utility function to check to see whether or not cron has been disabled from rt.ini
start_cron()
{
  if [ `$NIRTCFG --get section=RTLog,token=disableCron,value=false | tr "[:upper:]" "[:lower:]"` = "false" -o "$1" = "force" ]
  then
	[ "${VERBOSE}" != "no" ] && echo -n "Starting crond..."
	start-stop-daemon -S -b -n $(basename ${CROND}) -a $CROND -- $ARGS
	[ "${VERBOSE}" != "no" ] && echo "done."
  else
	[ "${VERBOSE}" != "no" ] && echo "Cron disabled from ni-rt.ini"
  fi
}

case "$1" in
	start)
		start_cron
	;;
	stop)
		echo -n "Stopping crond... "
		start-stop-daemon -K -n $(basename ${CROND})
		echo "done."
	;;
	restart)
		echo -n "Restarting crond... "
	 	$0 stop
		$0 start
	;;
	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
