#!/bin/sh

python /usr/lib/python2.7/site-packages/salt-tests/tests/runtests.py \
    --ptest-out \
    --no-report \
    --transport=tcp \
    --run-destructive \
    -n integration.modules.test_system \
    -n integration.modules.test_timezone \
    -n integration.modules.test_shadow \
    -n integration.states.test_user \
    -n integration.modules.test_groupadd \
    -n integration.modules.test_nilrt_ip \
