#!/bin/sh

# Kill any salt test processes which may be left around from orphaned test
# runs.
killall -q cli_master.py
killall -q cli_syndic.py
killall -q cli_minion.py
killall -q cli_run.py

python /usr/lib/python3.5/site-packages/salt-tests/tests/runtests.py \
    --ptest-out \
    --no-report \
    --transport=tcp \
    --run-destructive \
    -n unit.modules.test_opkg \
    -n integration.modules.test_system \
    -n integration.modules.test_timezone \
    -n integration.modules.test_shadow \
    -n integration.states.test_user \
    -n integration.modules.test_groupadd \
    -n integration.modules.test_nilrt_ip \
