#!/bin/sh

python /usr/lib/python2.7/site-packages/salt-tests/tests/runtests.py \
    --ptest-out \
    --transport=tcp \
    --run-destructive \
    -n integration.modules.system \
    -n integration.modules.timezone \
    -n integration.modules.shadow \
    -n integration.states.user \
    -n integration.modules.groupadd \


