# Why do we need this patch?


# The following perl ptests:

#   - dist/ExtUtils-ParseXS/t/001-basic
#   - dist/ExtUtils-ParseXS/t/002-more
#   - dist/ExtUtils-ParseXS/t/003-usage
#   - cpan/ExtUtils-Constant/t/Constant
#   - cpan/ExtUtils-MakeMaker/t/02-xsdynamic

# are erroring out with:
# | /usr/lib/perl/ptest/perl_langinfo.h:8:10: fatal error:
# xconfig.h: No such file or directory
# |     8 | #include "xconfig.h"

# xconfig.h contains references to the build host architecture and was removed by commit:
# https://github.com/ni/openembedded-core/commit/2e0f30c4680221c693495e3a0327378d502a518b

# However, it is still included from various other places including these tests, and we are
# still depending on build host architecture data by including the patches from perl-cross
# recipe, a dependency to perl recipe.

# xconfig.h was added back as a copy step in the commit:
# https://github.com/ni/openembedded-core/commit/f90922cdeef5a6a4b711c5be2156c05bdb20d5b5
# but was not added back in perl-ptest include file.

# Borrowed the logic from the above commit to make a copy of config.h that is specific to
# the target architecture. The changes in this commit fixes the test failures.

# Upstream-Status: Not appropriate for upstream as they seemed to reject one of the patches
# that was targeted for the upstream image. They mentioned that including the packages to
# fix the tests running in the yocto image (core-image-ptest-perl) would increase the image
# size and they do not want this approach even if it comes at a cost of skipping those
# tests. They said they are OK to live with those skipping tests.

do_install_ptest () {
	mkdir -p ${D}${PTEST_PATH}
	sed -e "s:\/usr\/local:${bindir}:g" -i cpan/version/t/*
	sed -e "s:\/opt:\/usr:" -i Porting/add-package.pl
	sed -e "s:\/local\/gnu\/:\/:" -i hints/cxux.sh
	tar -c --exclude=try --exclude=a.out --exclude='*.o' --exclude=libperl.so* --exclude=[Mm]akefile --exclude=hostperl \
	    --exclude=cygwin --exclude=os2 --exclude=djgpp --exclude=qnx --exclude=symbian --exclude=haiku \
	    --exclude=vms --exclude=vos --exclude=NetWare --exclude=amigaos4  --exclude=buildcustomize.pl \
	    --exclude='win32/config.*' --exclude=plan9 --exclude=README.plan9 --exclude=perlplan9.pod --exclude=Configure \
	    --exclude=veryclean.sh --exclude=realclean.sh  --exclude=getioctlsizes \
	    --exclude=dl_aix.xs --exclude=sdbm.3 --exclude='cflags.SH' --exclude=[Mm]akefile.old \
		--exclude=miniperl --exclude=generate_uudmap --exclude=patches --exclude='config.log' * | ( cd ${D}${PTEST_PATH} && tar -x )

	ln -sf ${bindir}/perl ${D}${PTEST_PATH}/t/perl

	# xconfig.h contains references to build host architecture, and yet is included from various other places.
	# To make it reproducible let's make it a copy of config.h patch that is specific to the target architecture.
	# It is believed that the original header is the product of building miniperl (a helper executable built with host compiler).
	cp ${D}${libdir}/perl5/${PV}/${TARGET_ARCH}-linux/CORE/config.h ${D}${PTEST_PATH}/xconfig.h

	# Remove build host references from various scattered files...
	find "${D}${PTEST_PATH}" \
	     \( -name '*.PL' -o -name 'myconfig' -o -name 'cflags' -o -name '*.pl' -o -name '*.sh' -o -name '*.pm' \
	     -o -name 'h2xs' -o -name 'h2ph' \
	     -o -name '*.h' -o -name 'config.sh-*' -o -name 'pod2man'  -o -name 'pod2text' -o -name 'Makefile.config' \) \
	    -type f -exec sed -i \
	       -e "s,${D},,g" \
	       -e "s,--sysroot=${STAGING_DIR_HOST},,g" \
	       -e "s,-isystem${STAGING_INCDIR} ,,g" \
	       -e 's^${DEBUG_PREFIX_MAP_REGEX}^^g' \
	       -e "s,${STAGING_BINDIR_NATIVE}/perl-native/,${bindir}/,g" \
	       -e "s,${STAGING_LIBDIR},${libdir},g" \
	       -e "s,${STAGING_BINDIR},${bindir},g" \
	       -e "s,${STAGING_INCDIR},${includedir},g" \
	       -e "s,${STAGING_BINDIR_NATIVE}/,,g" \
	       -e "s,${STAGING_BINDIR_TOOLCHAIN}/${TARGET_PREFIX},${bindir},g" \
	       -e 's:${RECIPE_SYSROOT_NATIVE}::g' \
	       -e 's:${RECIPE_SYSROOT}::g' \
	        {} +

	 # Remove a useless timestamp...
	 sed -i -e '/Autogenerated starting on/d' ${D}${PTEST_PATH}/lib/unicore/mktables.lst

	 # Remove files with host-specific configuration for building native binaries
	 rm ${D}${PTEST_PATH}/Makefile.config ${D}${PTEST_PATH}/xconfig.sh
}
