#!/bin/bash
# This is a custom init file for the NILRT container, that does some fixups and
# then executes the container's CMD..

# Create softlinks to wrapper scripts for fw_printenv and fw_setenv
if [ -f /sbin/fw_printenv.wrapper ]; then
    ln -sf /sbin/fw_printenv.wrapper /sbin/fw_printenv
fi

if [ -f /sbin/fw_setenv.wrapper ]; then
    ln -sf /sbin/fw_setenv.wrapper /sbin/fw_setenv
fi

fw_setenv serial# $(hostname)

setcap CAP_SYS_TIME+ep /sbin/hwclock.util-linux

/etc/init.d/populateconfig start

if [ -f /etc/init.d/niauth ]; then
    /etc/init.d/niauth start
fi

/etc/init.d/run-postinsts start

# Execute the CMD passed to the container
exec "$@"
