#!/bin/bash

if [ "$(docker images -q cyclictest-container:latest)" = "" ]; then
    echo "Building cyclictest-container..."
    DOCKER_BUILDKIT=0 \
        docker build -t cyclictest-container --network=host ./cyclictest-container
    if [ "$(docker images -q cyclictest-container:latest)" = "" ]; then
        echo "Failed to build cyclictest-container"
        exit 77
    fi
fi

if [ "$(docker images -q parallel-container:latest)" = "" ]; then
    echo "Building parallel-container..."
    DOCKER_BUILDKIT=0 \
        docker build -t parallel-container --network=host ./parallel-container
    if [ "$(docker images -q parallel-container:latest)" = "" ]; then
        echo "Failed to build parallel-container"
        exit 77
    fi
fi

exit 0
