#!/bin/bash
source "$(dirname "$0")"/common.cfg
source /home/admin/.iperf.info

case "$1" in
	check)
		if [ -z "$IPERF_SERVER" ]; then
			echo "Warning: iperf server not configured; skipping iperf based network load test."
			echo "Create/edit /home/admin/.iperf.info file with IPERF_SERVER=<server> and IPERF_PORT=<port> to configure a server to connect to for this test."
			echo "SKIP: test_kernel_cyclictest_iperf"
			exit 77
		fi
		if [ ! -z "$IPERF_PORT" ]; then
			iperf3 -c "$IPERF_SERVER" -p "$IPERF_PORT" -t 1 > /dev/null 2>&1
		else
			iperf3 -c "$IPERF_SERVER" -t 1 > /dev/null 2>&1
		fi
		if [ $? -ne 0 ]; then
			echo "ERROR: iperf server not reachable; skipping iperf based network load test."
			echo "SKIP: test_kernel_cyclictest_iperf"
			exit 77
		fi
		;;
	start)
		if [ ! -z "$IPERF_PORT" ]; then
			iperf3 -c "$IPERF_SERVER" -p "$IPERF_PORT" -t 36000 --logfile "$LOG_DIR/iperf-`date +'%Y_%m_%d-%H_%M_%S'`.log" &
		else
			iperf3 -c "$IPERF_SERVER" -t 36000 --logfile "$LOG_DIR/iperf-`date +'%Y_%m_%d-%H_%M_%S'`.log" &
		fi
		;;
	stop)
		killall -INT iperf3 > /dev/null 2>&1
		;;
	*)
		echo "Usage: $0 {check|start|stop}"
		exit 1
		;;
esac

exit 0
