#!/bin/bash
source "$(dirname "$0")"/common.cfg

case "$#" in
	1)
		docker run --privileged --network=host \
		       -v ${LOG_DIR}:${LOG_DIR} \
		       -v ${TEST_DIR}:${TEST_DIR} \
		       -v /home/admin:/home/admin \
		       -v /usr/share/fw_printenv:/usr/share/fw_printenv \
		       -v /sbin/fw_printenv:/sbin/fw_printenv \
		       -v /usr/share/nisysinfo:/usr/share/nisysinfo \
		       -v /etc/os-release:/etc/os-release \
		       -v /dev:/dev \
		       -w ${TEST_DIR} \
		       -t cyclictest-container \
		       "${TEST_DIR}/run-cyclictest" "$1"
		CYCLICTEST_RESULT=$?
		;;
	2)
		docker run --privileged --network=host \
		       --cpuset-cpus "$2" \
		       -v ${LOG_DIR}:${LOG_DIR} \
		       -v ${TEST_DIR}:${TEST_DIR} \
		       -v /home/admin:/home/admin \
		       -v /usr/share/fw_printenv:/usr/share/fw_printenv \
		       -v /sbin/fw_printenv:/sbin/fw_printenv \
		       -v /usr/share/nisysinfo:/usr/share/nisysinfo \
		       -v /etc/os-release:/etc/os-release \
		       -v /dev:/dev \
		       -w ${TEST_DIR} \
		       -t cyclictest-container \
		       "${TEST_DIR}/run-cyclictest" "$1"
		;;
	*)
		echo echo "Usage: $0 {test_name} [{cpu}]"
		exit 1
		;;
esac
