#! /bin/sh

# Copyright (C) 2015 National Instruments
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

set -e

exec 3>/dev/null
[ "${VERBOSE}" != "no" ] && exec 3>&1

rtctl_error() {
    echo "Error $1"
    echo "Is /etc/rtgroups is missing or corrupt?"
    exit 1
}

case "$1" in
    start|restart|reload|force-reload)
        echo -n "Setting kernel thread priorities: "
        echo "" >&3
        rtctl reset >&3 || rtctl_error "$?"
        echo "Done"
        ;;
    stop)
        # no op
        ;;
    *)
        echo >&2 "Usage: $0 {start|stop|restart|reload|force-reload}"
        exit 1
        ;;
esac

