#!/bin/bash
set -euo pipefail

# close stdin
exec 0<&-

# redirect stderr to stdout
exec 2>&1

TEST_NAME="grpcio_smoke_ptest"

error_exit_handler () {
    set +e
    local lineno=$1
    local msg=$2
    echo "ERROR on line $lineno: $msg" 1>&2
    echo "FAIL: $TEST_NAME"
    exit 1
}

trap 'error_exit_handler ${LINENO} "$BASH_COMMAND"' ERR

# Run the python code and expect the server to respond with a known error message
# about the NI System Configuration API not being installed.  The API is not
# required, the fact that the server responds is enough for the test to pass.
testtxt=`python enumerate-device.py`
[ "$testtxt" == "The NI System Configuration API is not installed on the server." ]

echo "PASS: $TEST_NAME"
exit 0
