SUMMARY = "Packages for building essential/core kernel modules"
LICENSE = "MIT"

inherit packagegroup

RDEPENDS:${PN} = "\
	kernel-module-8021q \
	kernel-module-aacraid \
	kernel-module-act-skbedit \
	kernel-module-aesni-intel \
	kernel-module-af-alg \
	kernel-module-af-key \
	kernel-module-agpgart \
	kernel-module-ah4 \
	kernel-module-ah6 \
	kernel-module-algif-skcipher \
	kernel-module-ar5523 \
	kernel-module-arc4 \
	kernel-module-arcmsr \
	kernel-module-arp-tables \
	kernel-module-arpt-mangle \
	kernel-module-arptable-filter \
	kernel-module-asix \
	kernel-module-async-memcpy \
	kernel-module-async-pq \
	kernel-module-async-raid6-recov \
	kernel-module-async-tx \
	kernel-module-async-xor \
	kernel-module-at76c50x-usb \
	kernel-module-ath \
	kernel-module-ath6kl-core \
	kernel-module-ath6kl-sdio \
	kernel-module-ath6kl-usb \
	kernel-module-atkbd \
	kernel-module-auth-rpcgss \
	kernel-module-authenc \
	kernel-module-authencesn \
	kernel-module-ax88179-178a \
	kernel-module-ax88796b \
	kernel-module-backlight \
	kernel-module-blocklayoutdriver \
	kernel-module-bluetooth \
	kernel-module-bochs \
	kernel-module-bonding \
	kernel-module-br-netfilter \
	kernel-module-bridge \
	kernel-module-bsd-comp \
	kernel-module-btbcm \
	kernel-module-btintel \
	kernel-module-btrtl \
	kernel-module-btusb \
	kernel-module-button \
	kernel-module-carl9170 \
	kernel-module-catc \
	kernel-module-ccm \
	kernel-module-cdc-acm \
	kernel-module-cdc-eem \
	kernel-module-cdc-ether \
	kernel-module-cdc-ncm \
	kernel-module-cdc-subset \
	kernel-module-cfg80211 \
	kernel-module-ch341 \
	kernel-module-ch9200 \
	kernel-module-chacha-x86-64 \
	kernel-module-chipreg \
	kernel-module-cifs \
	kernel-module-cifs-arc4 \
	kernel-module-cifs-md4 \
	kernel-module-cls-basic \
	kernel-module-cls-u32 \
	kernel-module-cmac \
	kernel-module-coretemp \
	kernel-module-cp210x \
	kernel-module-cpuid \
	kernel-module-crc-ccitt \
	kernel-module-crc-itu-t \
	kernel-module-crc7 \
	kernel-module-crc8 \
	kernel-module-crypto-null \
	kernel-module-crypto-simd \
	kernel-module-ctr \
	kernel-module-curve25519-x86-64 \
	kernel-module-cuse \
	kernel-module-dax \
	kernel-module-deflate \
	kernel-module-digi-acceleport \
	kernel-module-dm-crypt \
	kernel-module-dm-mod \
	kernel-module-dm-raid \
	kernel-module-dmi-sysfs \
	kernel-module-drbg \
	kernel-module-drm \
	kernel-module-drm-buddy \
	kernel-module-drm-display-helper \
	kernel-module-drm-kms-helper \
	kernel-module-drm-shmem-helper \
	kernel-module-drm-suballoc-helper \
	kernel-module-drm-ttm-helper \
	kernel-module-drm-vram-helper \
	kernel-module-dvb-core \
	kernel-module-dwc3 \
	kernel-module-dwc3-haps \
	kernel-module-dwc3-pci \
	kernel-module-e100 \
	kernel-module-e1000 \
	kernel-module-e1000e \
	kernel-module-ecc \
	kernel-module-ecdh-generic \
	kernel-module-echainiv \
	kernel-module-eeprom-93cx6 \
	kernel-module-em-cmp \
	kernel-module-esp4 \
	kernel-module-esp4-offload \
	kernel-module-esp6 \
	kernel-module-esp6-offload \
	kernel-module-essiv \
	kernel-module-ezusb \
	kernel-module-failover \
	kernel-module-ff-memless \
	kernel-module-firewire-core \
	kernel-module-firewire-net \
	kernel-module-firewire-ohci \
	kernel-module-firewire-sbp2 \
	kernel-module-ftdi-sio \
	kernel-module-fuse \
	kernel-module-g-ether \
	kernel-module-gcm \
	kernel-module-geniv \
	kernel-module-ghash-generic \
	kernel-module-grace \
	kernel-module-gre \
	kernel-module-hid-lg-g15 \
	kernel-module-hid-logitech \
	kernel-module-hid-logitech-dj \
	kernel-module-hid-logitech-hidpp \
	kernel-module-hid-microsoft \
	kernel-module-hid-multitouch \
	kernel-module-hid-penmount \
	kernel-module-hyperv-keyboard \
	kernel-module-i2c-algo-bit \
	kernel-module-i2c-ccgx-ucsi \
	kernel-module-i2c-designware-core \
	kernel-module-i2c-designware-pci \
	kernel-module-i2c-designware-platform \
	kernel-module-i2c-dev \
	kernel-module-i2c-i801 \
	kernel-module-i2c-mux \
	kernel-module-i2c-smbus \
	kernel-module-i40e \
	kernel-module-i8042 \
	kernel-module-i915 \
	kernel-module-ib-cm \
	kernel-module-ib-core \
	kernel-module-ib-uverbs \
	kernel-module-igb \
	kernel-module-igbvf \
	kernel-module-igc \
	kernel-module-inet-diag \
	kernel-module-intel-gtt \
	kernel-module-intel-rng \
	kernel-module-ip-gre \
	kernel-module-ip-tables \
	kernel-module-ip-tunnel \
	kernel-module-ip-vs \
	kernel-module-ip6-tables \
	kernel-module-ip6-udp-tunnel \
	kernel-module-ip6t-ah \
	kernel-module-ip6t-eui64 \
	kernel-module-ip6t-frag \
	kernel-module-ip6t-hbh \
	kernel-module-ip6t-ipv6header \
	kernel-module-ip6t-mh \
	kernel-module-ip6t-reject \
	kernel-module-ip6t-rt \
	kernel-module-ip6table-filter \
	kernel-module-ip6table-mangle \
	kernel-module-ip6table-raw \
	kernel-module-ip6table-security \
	kernel-module-ipcomp \
	kernel-module-ipcomp6 \
	kernel-module-ipheth \
	kernel-module-ipip \
	kernel-module-ipt-ah \
	kernel-module-ipt-ecn \
	kernel-module-ipt-reject \
	kernel-module-iptable-filter \
	kernel-module-iptable-mangle \
	kernel-module-iptable-nat \
	kernel-module-iptable-raw \
	kernel-module-iptable-security \
	kernel-module-ipv6 \
	kernel-module-iw-cm \
	kernel-module-ixgbe \
	kernel-module-jitterentropy-rng \
	kernel-module-kaweth \
	kernel-module-l2tp-core \
	kernel-module-l2tp-debugfs \
	kernel-module-l2tp-eth \
	kernel-module-l2tp-ip \
	kernel-module-l2tp-ip6 \
	kernel-module-l2tp-netlink \
	kernel-module-lcd \
	kernel-module-leds-nic78bx \
	kernel-module-lg-vl600 \
	kernel-module-libarc4 \
	kernel-module-libchacha \
	kernel-module-libchacha20poly1305 \
	kernel-module-libcomposite \
	kernel-module-libcurve25519 \
	kernel-module-libcurve25519-generic \
	kernel-module-libpoly1305 \
	kernel-module-libps2 \
	kernel-module-libsas \
	kernel-module-llc \
	kernel-module-lockd \
	kernel-module-lpc-ich \
	kernel-module-lzo \
	kernel-module-lzo-compress \
	kernel-module-lzo-rle \
	kernel-module-mac80211 \
	kernel-module-mc \
	kernel-module-mc44s803 \
	kernel-module-md-mod \
	kernel-module-mdio \
	kernel-module-mfd-core \
	kernel-module-microchip \
	kernel-module-mii \
	kernel-module-mlx5-core \
	kernel-module-mlx5-ib \
	kernel-module-mos7720 \
	kernel-module-mos7840 \
	kernel-module-mousedev \
	kernel-module-msr \
	kernel-module-mt20xx \
	kernel-module-mt7601u \
	kernel-module-mtd \
	kernel-module-mvsas \
	kernel-module-net-failover \
	kernel-module-net1080 \
	kernel-module-netconsole \
	kernel-module-netfs \
	kernel-module-nf-conncount \
	kernel-module-nf-conntrack \
	kernel-module-nf-conntrack-amanda \
	kernel-module-nf-conntrack-broadcast \
	kernel-module-nf-conntrack-ftp \
	kernel-module-nf-conntrack-h323 \
	kernel-module-nf-conntrack-irc \
	kernel-module-nf-conntrack-netbios-ns \
	kernel-module-nf-conntrack-netlink \
	kernel-module-nf-conntrack-pptp \
	kernel-module-nf-conntrack-sane \
	kernel-module-nf-conntrack-sip \
	kernel-module-nf-conntrack-snmp \
	kernel-module-nf-conntrack-tftp \
	kernel-module-nf-defrag-ipv4 \
	kernel-module-nf-defrag-ipv6 \
	kernel-module-nf-dup-ipv4 \
	kernel-module-nf-dup-ipv6 \
	kernel-module-nf-dup-netdev \
	kernel-module-nf-flow-table \
	kernel-module-nf-flow-table-inet \
	kernel-module-nf-log-syslog \
	kernel-module-nf-nat \
	kernel-module-nf-nat-amanda \
	kernel-module-nf-nat-ftp \
	kernel-module-nf-nat-h323 \
	kernel-module-nf-nat-irc \
	kernel-module-nf-nat-pptp \
	kernel-module-nf-nat-sip \
	kernel-module-nf-nat-snmp-basic \
	kernel-module-nf-nat-tftp \
	kernel-module-nf-reject-ipv4 \
	kernel-module-nf-reject-ipv6 \
	kernel-module-nf-socket-ipv4 \
	kernel-module-nf-socket-ipv6 \
	kernel-module-nf-synproxy-core \
	kernel-module-nf-tables \
	kernel-module-nf-tproxy-ipv4 \
	kernel-module-nf-tproxy-ipv6 \
	kernel-module-nfnetlink \
	kernel-module-nfnetlink-cttimeout \
	kernel-module-nfnetlink-log \
	kernel-module-nfnetlink-osf \
	kernel-module-nfnetlink-queue \
	kernel-module-nfs \
	kernel-module-nfs-layout-flexfiles \
	kernel-module-nfs-layout-nfsv41-files \
	kernel-module-nfsv2 \
	kernel-module-nfsv3 \
	kernel-module-nfsv4 \
	kernel-module-nft-chain-nat \
	kernel-module-nft-compat \
	kernel-module-nft-connlimit \
	kernel-module-nft-ct \
	kernel-module-nft-dup-ipv4 \
	kernel-module-nft-dup-ipv6 \
	kernel-module-nft-dup-netdev \
	kernel-module-nft-fib \
	kernel-module-nft-fib-inet \
	kernel-module-nft-fib-ipv4 \
	kernel-module-nft-fib-ipv6 \
	kernel-module-nft-fib-netdev \
	kernel-module-nft-fwd-netdev \
	kernel-module-nft-hash \
	kernel-module-nft-limit \
	kernel-module-nft-log \
	kernel-module-nft-masq \
	kernel-module-nft-nat \
	kernel-module-nft-numgen \
	kernel-module-nft-osf \
	kernel-module-nft-queue \
	kernel-module-nft-quota \
	kernel-module-nft-redir \
	kernel-module-nft-reject \
	kernel-module-nft-reject-inet \
	kernel-module-nft-reject-ipv4 \
	kernel-module-nft-reject-ipv6 \
	kernel-module-nft-reject-netdev \
	kernel-module-nft-socket \
	kernel-module-nft-synproxy \
	kernel-module-nft-tproxy \
	kernel-module-nft-tunnel \
	kernel-module-nft-xfrm \
	kernel-module-nic7018-wdt \
	kernel-module-nlmon \
	kernel-module-nls-ucs2-utils \
	kernel-module-ntfs \
	kernel-module-ntfs3 \
	kernel-module-nvme-fabrics \
	kernel-module-nvme-rdma \
	kernel-module-p8022 \
	kernel-module-pcrypt \
	kernel-module-pegasus \
	kernel-module-phy-generic \
	kernel-module-phylink \
	kernel-module-pl2303 \
	kernel-module-plusb \
	kernel-module-poly1305-x86-64 \
	kernel-module-ppp-async \
	kernel-module-ppp-deflate \
	kernel-module-ppp-generic \
	kernel-module-ppp-synctty \
	kernel-module-psmouse \
	kernel-module-psnap \
	kernel-module-qcserial \
	kernel-module-r8152 \
	kernel-module-r8153-ecm \
	kernel-module-radeon \
	kernel-module-raid0 \
	kernel-module-raid1 \
	kernel-module-raid10 \
	kernel-module-raid456 \
	kernel-module-raid6-pq \
	kernel-module-rdma-cm \
	kernel-module-rdma-ucm \
	kernel-module-rndis-host \
	kernel-module-rng-core \
	kernel-module-rpcrdma \
	kernel-module-rpcsec-gss-krb5 \
	kernel-module-rt2500usb \
	kernel-module-rt2800lib \
	kernel-module-rt2800usb \
	kernel-module-rt2x00lib \
	kernel-module-rt2x00usb \
	kernel-module-rt73usb \
	kernel-module-rtl-usb \
	kernel-module-rtl8150 \
	kernel-module-rtl8187 \
	kernel-module-rtl8192c-common \
	kernel-module-rtl8192cu \
	kernel-module-rtlwifi \
	kernel-module-sata-mv \
	kernel-module-sata-sil \
	kernel-module-sch-multiq \
	kernel-module-sch-netem \
	kernel-module-scsi-transport-sas \
	kernel-module-scsi-transport-spi \
	kernel-module-sctp \
	kernel-module-sctp-diag \
	kernel-module-seqiv \
	kernel-module-serio \
	kernel-module-serport \
	kernel-module-sha3-generic \
	kernel-module-sha512-generic \
	kernel-module-sierra \
	kernel-module-sierra-net \
	kernel-module-sit \
	kernel-module-slhc \
	kernel-module-smsc \
	kernel-module-smsc75xx \
	kernel-module-smsc95xx \
	kernel-module-softdog \
	kernel-module-spi-nor \
	kernel-module-spi-pxa2xx-pci \
	kernel-module-spi-pxa2xx-platform \
	kernel-module-spidev \
	kernel-module-stp \
	kernel-module-sunrpc \
	kernel-module-sym53c8xx \
	kernel-module-tcp-diag \
	kernel-module-tda18271 \
	kernel-module-tda827x \
	kernel-module-tda8290 \
	kernel-module-tda9887 \
	kernel-module-tea5761 \
	kernel-module-tea5767 \
	kernel-module-tg3 \
	kernel-module-thunderbolt \
	kernel-module-tls \
	kernel-module-tmp421 \
	kernel-module-tpm \
	kernel-module-tpm-tis \
	kernel-module-tpm-tis-core \
	kernel-module-ts-bm \
	kernel-module-ts-fsm \
	kernel-module-ts-kmp \
	kernel-module-ttm \
	kernel-module-tulip \
	kernel-module-tuner-simple \
	kernel-module-tuner-types \
	kernel-module-tunnel4 \
	kernel-module-tunnel6 \
	kernel-module-u-ether \
	kernel-module-ubi \
	kernel-module-ubifs \
	kernel-module-udc-core \
	kernel-module-udp-tunnel \
	kernel-module-uio \
	kernel-module-uio-pci-generic \
	kernel-module-usb-f-ecm \
	kernel-module-usb-f-ecm-subset \
	kernel-module-usb-f-eem \
	kernel-module-usb-wwan \
	kernel-module-usbnet \
	kernel-module-usbserial \
	kernel-module-usbtouchscreen \
	kernel-module-uvc \
	kernel-module-uvcvideo \
	kernel-module-v4l2-async \
	kernel-module-v4l2-dv-timings \
	kernel-module-v4l2-fwnode \
	kernel-module-veth \
	kernel-module-video \
	kernel-module-videobuf2-common \
	kernel-module-videobuf2-memops \
	kernel-module-videobuf2-v4l2 \
	kernel-module-videobuf2-vmalloc \
	kernel-module-videodev \
	kernel-module-virtio \
	kernel-module-virtio-balloon \
	kernel-module-virtio-blk \
	kernel-module-virtio-console \
	kernel-module-virtio-dma-buf \
	kernel-module-virtio-gpu \
	kernel-module-virtio-input \
	kernel-module-virtio-mmio \
	kernel-module-virtio-net \
	kernel-module-virtio-pci \
	kernel-module-virtio-pci-legacy-dev \
	kernel-module-virtio-pci-modern-dev \
	kernel-module-virtio-ring \
	kernel-module-virtio-rng \
	kernel-module-virtio-scsi \
	kernel-module-vivaldi-fmap \
	kernel-module-vmwgfx \
	kernel-module-wacom-serial4 \
	kernel-module-whiteheat \
	kernel-module-wireguard \
	kernel-module-wmi \
	kernel-module-wmi-bmof \
	kernel-module-x-tables \
	kernel-module-x86-pkg-temp-thermal \
	kernel-module-xc2028 \
	kernel-module-xc4000 \
	kernel-module-xc5000 \
	kernel-module-xfrm-algo \
	kernel-module-xfrm-ipcomp \
	kernel-module-xfrm-user \
	kernel-module-xfrm4-tunnel \
	kernel-module-xfrm6-tunnel \
	kernel-module-xor \
	kernel-module-xt-addrtype \
	kernel-module-xt-classify \
	kernel-module-xt-cluster \
	kernel-module-xt-comment \
	kernel-module-xt-connbytes \
	kernel-module-xt-connlimit \
	kernel-module-xt-connmark \
	kernel-module-xt-conntrack \
	kernel-module-xt-cpu \
	kernel-module-xt-dccp \
	kernel-module-xt-devgroup \
	kernel-module-xt-dscp \
	kernel-module-xt-ecn \
	kernel-module-xt-esp \
	kernel-module-xt-hashlimit \
	kernel-module-xt-helper \
	kernel-module-xt-hl \
	kernel-module-xt-idletimer \
	kernel-module-xt-iprange \
	kernel-module-xt-ipvs \
	kernel-module-xt-l2tp \
	kernel-module-xt-length \
	kernel-module-xt-limit \
	kernel-module-xt-log \
	kernel-module-xt-mac \
	kernel-module-xt-mark \
	kernel-module-xt-masquerade \
	kernel-module-xt-multiport \
	kernel-module-xt-nat \
	kernel-module-xt-netmap \
	kernel-module-xt-nflog \
	kernel-module-xt-nfqueue \
	kernel-module-xt-osf \
	kernel-module-xt-owner \
	kernel-module-xt-pkttype \
	kernel-module-xt-policy \
	kernel-module-xt-quota \
	kernel-module-xt-rateest \
	kernel-module-xt-realm \
	kernel-module-xt-recent \
	kernel-module-xt-redirect \
	kernel-module-xt-sctp \
	kernel-module-xt-state \
	kernel-module-xt-statistic \
	kernel-module-xt-string \
	kernel-module-xt-tcpmss \
	kernel-module-xt-tcpudp \
	kernel-module-xt-tee \
	kernel-module-xt-time \
	kernel-module-xt-u32 \
	kernel-module-zaurus \
	kernel-module-zd1201 \
	kernel-module-zd1211rw \
	kernel-module-zstd \
	kernel-module-zstd-compress \
	"
