#!/bin/bash
### BEGIN INIT INFO
# Provides:          nicleanefivars
# Required-Start:    $mountvirtfs
# Required-Stop:     
# Default-Start:     S
# Default-Stop:      
# Short-Description: nicleanefivars
# Description:       This is a script that cleans old efi-pstore information.
### END INIT INFO

# Previous kernels may have stored kernel crash information in EFI for
# systemd to retrieve later. However, this version of NI Linux RT does
# not use systemd and therefore does not have a way to meaningfully
# utilize this information. In order to prevent future issues due to
# exhaustion of EFI variable storage, erase all prior dump information.

NAME=nicleanefivars
SCRIPTNAME=/etc/init.d/$NAME

EFI_CRASH_CLEANUP=y

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# no-op if EFI_CRASH_CLEANUP=n is set in /etc/default/nicleanefivars
case "$EFI_CRASH_CLEANUP" in
    [Nn]*)
        exit 0
        ;;
esac

case "$1" in
    start)
        LINUX_EFI_CRASH_GUID="cfc8fc79-be2e-4ddc-97f0-9f98bfe298a0"
        find /sys/firmware/efi/efivars -name "*-${LINUX_EFI_CRASH_GUID}" -exec /bin/rm {} +
        ;;
    stop|status|reload|restart|force-reload)
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start}" >&2
        exit 3
        ;;
esac

exit 0
