#!/bin/bash
SCRIPT_NAME="niclosedisks"

# begin output
echo -n "$SCRIPT_NAME: " || true

# close stdin
exec 0<&-

function error () {
    echo >&2 "$SCRIPT_NAME: ERROR: $*"
    exit 1
}

[ "$#" -gt 0 ] || error "Must provide at least one arg"
[ "$1" == "stop" ] || error "Only 'stop' operation is supported"

# Remount /var/volatile and /dev, used by nilrtdiskcrypt
mounted_volatile=true
mounted_dev=true
mount -t tmpfs tmpfs /var/volatile || mounted_volatile=false
mount -o remount,rw -t devtmpfs devtmpfs /dev || mounted_dev=false

# suppress stdout and stderr if echo fails, so that subsequent
#  tools dont error out when prints occur
if ! echo ""; then
    exec 1>/dev/null
fi
if ! echo 1>&2 ""; then
    exec 2>&1
fi

CONFIGFS_DEV="/dev/$(lsblk -l -n -o PARTLABEL,NAME | grep '^niconfig '| tr -s ' ' | cut -d' ' -f2)"
ROOTFS_DEV="/dev/$(lsblk -l -n -o PARTLABEL,NAME | grep '^nirootfs '| tr -s ' ' | cut -d' ' -f2)"

# setup VERBOSE flag for nilrtdiskcrypt
if [ "${VERBOSE+x}" == "yes" ]; then
    export VERBOSE=1
else
    export VERBOSE=0
fi

if [ -f /etc/natinst/safemode ]; then
    nilrtdiskcrypt_close -d "$CONFIGFS_DEV" -d "$ROOTFS_DEV"
else
    nilrtdiskcrypt_close -d "$CONFIGFS_DEV"
fi

# Umount /var/volatile and /dev, if mounted earlier
$mounted_dev && umount -f -r /dev
$mounted_volatile && umount /var/volatile

# everything finished, end output
echo "OK"
