#!/bin/sh
# Copyright (c) 2012-2025 National Instruments.
# All rights reserved.

debugfs_path="/sys/kernel/debug"
tracefs_path="$debugfs_path/tracing"
tracing_on_path="$tracefs_path/tracing_on"
trace_marker_path="$tracefs_path/trace_marker"

# tracefs is created in a weird state; poke it to make it real
touch -c $tracefs_path/dummy

# Change the permissions so lvrt user can control ftrace
chmod a+rx $debugfs_path
chmod a+rx $tracefs_path
chown lvuser $tracing_on_path
chown lvuser $trace_marker_path
