#!/bin/sh
# Copyright (c) 2012-2023 National Instruments.
# All rights reserved.

# Exit early if LabVIEW RT does not use cgroup-v1

# Source cgroup version detection
. /usr/share/initscripts-nilrt/lvrt-cgroup.sh
identify_lvrt_cgroup_version || exit 0

if [ "$LVRT_CGROUP_VERSION" -eq 1 ]; then
	# cgroup v1 logic
	[ "${VERBOSE}" != "no" ] && echo -n "Starting nicreatecpusets (cgroup v1):"
	mkdir -p /dev/cgroup/cpuset
	mount -t cpuset none /dev/cgroup/cpuset
	cd /dev/cgroup/cpuset

	for dir in LabVIEW_ScanEngine_set LabVIEW_tl_set system_set; do
		mkdir -p "$dir"
		# cpus and mems cannot be empty while tasks are added to tasks file in a cpuset
		cat cpus > "./$dir/cpus"
		cat mems > "./$dir/mems"
	done

	while read TASK; do
		echo $TASK > "./system_set/tasks" 2> /dev/null
	done < "tasks"
	chown -R lvuser:ni /dev/cgroup/cpuset
	[ "${VERBOSE}" != "no" ] && echo "done"
elif [ "$LVRT_CGROUP_VERSION" -eq 2 ]; then
	# cgroup v2 logic: create /sys/fs/cgroup/ni and subgroups
	[ "${VERBOSE}" != "no" ] && echo -n "Starting nicreatecpusets (cgroup v2):"
	CGROUP2_ROOT="/sys/fs/cgroup"
	mount -t cgroup2 none "$CGROUP2_ROOT"
	cd "$CGROUP2_ROOT"
	# Enable cpuset controller in root
	echo "+cpuset" > cgroup.subtree_control
	# Create ni domain
	mkdir -p ni
	chown lvuser:ni ni
	cd ni
	# Enable cpuset controller in ni
	echo "+cpuset" > cgroup.subtree_control
	# Create subgroups and assign cpuset.cpus/mems if available
	for group in irq scanengine system time-critical timed-structures; do
		mkdir -p "$group"
		chown lvuser:ni "$group"
		[ -f "../cpuset.cpus" ] && cat ../cpuset.cpus > "$group/cpuset.cpus"
		[ -f "../cpuset.mems" ] && cat ../cpuset.mems > "$group/cpuset.mems"
	done
	# Assign tasks (v2: use cgroup.procs)
	if [ -f "../tasks" ]; then
		while read TASK; do
			echo $TASK > system/cgroup.procs 2> /dev/null
		done < "../tasks"
	fi
	[ "${VERBOSE}" != "no" ] && echo "done"
else
	[ "${VERBOSE}" != "no" ] && echo "Unknown cgroup version: $LVRT_CGROUP_VERSION. Exiting."
	exit 0
fi
