#! /bin/sh

if [[ -f /usr/lib/nisetbootmode.functions ]]; then
	source /usr/lib/nisetbootmode.functions
else
	echo "Missing file:/usr/lib/nisetbootmode.functions"
	exit 1
fi

case "$1" in
  start)
    # The default boot mode is always "default"
    [ -f $BOOT_MODE_INPUT ] && rm $BOOT_MODE_INPUT
    ;;
  stop)
    # Will hit checkbootmode just before exit 0 below
    ;;
  *)
    exit 1
    ;;
esac

checkbootmode

exit 0

