#!/bin/sh
# Copyright (c) 2012-2013 National Instruments.
# All rights reserved.
[ "${VERBOSE}" != "no" ] && echo -n "Setting up IRQ priority for deterministic devices:"

#IRQ=61 is used by NI-RIO device on arm
#IRQ=16 is used by NI-RIO device on x64

if [ $(uname -m) = "armv7l" ]; then
  echo 96 > /proc/irq/61/priority
else
  PS=`ps -eo comm,pid | grep -sF -m 1 "irq/16-niriochi" | awk '{print $2}'`
  if [ "${PS}" != "" ]; then
    chrt -pf 96 $PS
  fi
fi

[ "${VERBOSE}" != "no" ] && echo "done"
