#! /bin/sh
# Copyright (c) 2012-2013 National Instruments.
# All rights reserved.

status_led=/usr/bin/status_led

# switch LED watchdog from boot mode to user mode, and turn off the LED
$status_led init

