#!/bin/sh
# Copyright (c) 2012-2013 National Instruments.
# All rights reserved.

if [ "$1" = "start" ]
then
	#check if the system is in reset state
	reset_state=`/sbin/fw_printenv -n sys_reset 2>&1`
	if [ "$reset_state" = "true" ]; then
		#restore default environmnet vars
		cp -f /boot/grub/grubenv.bak /boot/grub/grubenv
		#do an ip reset
		mkdir -p /tmp/ip_reset_dir
		/usr/local/natinst/bin/ninetcfgutil pulldefault -d /tmp/ip_reset_dir -g primary
		rm -rf /tmp/ip_reset_dir
	fi

	if [ -x /usr/local/natinst/bin/nirtcfg ]; then
		[ "${VERBOSE}" != "no" ] && echo "Migrating bootloader env into ni-rt.ini"
		/usr/local/natinst/bin/nirtcfg --migrate

		# If IPReset.enabled was true on boot, the ip reset functionality is complete and need not stay set
		IPRESET=`/usr/local/natinst/bin/nirtcfg --get section=SystemSettings,token="IPReset.enabled",value=false | tr "[:upper:]" "[:lower:]"`
		if [ $IPRESET != "false" ]; then
			/usr/local/natinst/bin/nirtcfg --set section=SystemSettings,token="IPReset.enabled",value=false
		fi
	fi

	# TODO: review this sharing of settings between safe (restore?) mode and
	#       run mode. If we want to keep some or all of it, consider merging
	#       the timezone change from os-common's populateconfig as well
	mkdir -p /etc/natinst/share/ssh
	chmod -t /etc/natinst/share
	test -L /etc/natinst/share/localtime || ( rm -f /etc/natinst/share/localtime && ln -s /usr/share/zoneinfo/UTC /etc/natinst/share/localtime )

	# Ensure that /etc/natinst/share/timestamp exists and that /etc/timestamp symlinks to it.
	LCLTIMESTAMP="/etc/timestamp"
	SHAREDTIMESTAMP="/etc/natinst/share/timestamp"
	if [ -f $LCLTIMESTAMP ]; then
		# If /etc/natinst/share/timestamp doesn't exist, use /etc/timestamp to create it
		if [ ! -e $SHAREDTIMESTAMP ]; then
			mv $LCLTIMESTAMP $SHAREDTIMESTAMP
		fi
	elif [ ! -e $SHAREDTIMESTAMP ]; then
		touch $SHAREDTIMESTAMP
	fi

	ln -sf $SHAREDTIMESTAMP $LCLTIMESTAMP

fi
