#!/bin/sh
# Copyright (c) 2012-2013 National Instruments.
# All rights reserved.

if [ "$1" = "start" ]
then
	#check if the system is in reset state
	reset_state=`/sbin/fw_printenv -n sys_reset 2>&1`
	if [ "$reset_state" = "true" ]; then
		#restore default environmnet vars
		cp -f /boot/grub/grubenv.bak /boot/grub/grubenv
		#do an ip reset
		mkdir -p /tmp/ip_reset_dir
		ninetcfgutil pulldefault -d /tmp/ip_reset_dir -g primary
		rm -rf /tmp/ip_reset_dir
	fi

	if [ -x /usr/local/natinst/bin/nirtcfg ]; then
		[ "${VERBOSE}" != "no" ] && echo "Migrating bootloader env into ni-rt.ini"
		/usr/local/natinst/bin/nirtcfg --migrate

		# If IPReset.enabled was true on boot, the ip reset functionality is complete and need not stay set
		IPRESET=`/usr/local/natinst/bin/nirtcfg --get section=SystemSettings,token="IPReset.enabled",value=false | tr "[:upper:]" "[:lower:]"`
		if [ $IPRESET != "false" ]; then
			/usr/local/natinst/bin/nirtcfg --set section=SystemSettings,token="IPReset.enabled",value=false
		fi
	fi
fi
