#!/bin/bash
set -e
set -u
set -o pipefail

trap 'exitCode="$?"; set +e; echo "FAIL $0"; exit "$exitCode"' EXIT

echo "check that niopendisks runs right after sysfs"
ls -l "/etc/rcS.d/S04udev"
ls -l "/etc/rcS.d/S05niopendisks"
echo "OK"

echo "PASS $0"
trap - EXIT
