#!/bin/bash

source "${0%/*}/test-nisetcommitratio-common.sh"

declare -Ag REMAINING_TESTS=(
	["When memreserve directory is empty, commit ratio should not be changed"]=
	["When memreserves sum to zero, commit ratio should not be changed"]=
	["When memtotal=100MB and 10MB is reserved, the commit ratio should be set to 90"]=
	["When memtotal=100MB and 50MB is reserved, the commit ratio should be set to 50"]=
	["When memtotal=100MB and 10MB is reserved in two different files, the commit ratio should be set to 80"]=
	["When memtotal=100MB and 10MB is reserved in a file with comments, the commit ratio should be set to 90"]=
	["When memtotal=100 and 200MB is reserved, the commit ratio should be set to 25, and a warning should be printed"]=
	["When memtotal=0 and 10MB is reserved, the commit ratio should not be changed, and a warning should be printed"]=
	["When memtotal=64GB and 100MB is reserved, the commit ratio should be set to 99"]=
)

printf -v nisetcommitratio "%q " \
	env "MEMRESERVE_DIR=$tmp_memreserve_dir" \
	"OVERCOMMIT_RATIO=$tmp_overcommit_ratio" \
	"${nisetcommitratio:-/etc/init.d/nisetcommitratio}"

t="When memreserve directory is empty, commit ratio should not be changed"
test_start "$t"
$nisetcommitratio start >/dev/null || fail
[[ -f $tmp_overcommit_ratio ]] && fail
test_finish "$t"

t="When memreserves sum to zero, commit ratio should not be changed"
test_start "$t"
echo 0 > "$tmp_memreserve_dir/test1"
$nisetcommitratio start >/dev/null || fail
[[ -f $tmp_overcommit_ratio ]] && fail
test_finish "$t"

t="When memtotal=100MB and 10MB is reserved, the commit ratio should be set to 90"
test_start "$t"
echo 10 > "$tmp_memreserve_dir/test1"
MEMTOTAL_KB=102400 $nisetcommitratio start >/dev/null || fail
[[ -f $tmp_overcommit_ratio ]] && [[ $(<$tmp_overcommit_ratio) == 90 ]] || fail
test_finish "$t"

t="When memtotal=100MB and 50MB is reserved, the commit ratio should be set to 50"
test_start "$t"
echo 50 > "$tmp_memreserve_dir/test1"
MEMTOTAL_KB=102400 $nisetcommitratio start >/dev/null || fail
[[ -f $tmp_overcommit_ratio ]] && [[ $(<$tmp_overcommit_ratio) == 50 ]] || fail
test_finish "$t"

t="When memtotal=100MB and 10MB is reserved in two different files, the commit ratio should be set to 80"
test_start "$t"
echo 10 > "$tmp_memreserve_dir/test1"
echo 10 > "$tmp_memreserve_dir/test2"
MEMTOTAL_KB=102400 $nisetcommitratio start >/dev/null || fail
[[ -f $tmp_overcommit_ratio ]] && [[ $(<$tmp_overcommit_ratio) == 80 ]] || fail
test_finish "$t"

t="When memtotal=100MB and 10MB is reserved in a file with comments, the commit ratio should be set to 90"
test_start "$t"
cat > "$tmp_memreserve_dir/test1" <<EOF
# this is a comment
10

EOF
MEMTOTAL_KB=102400 $nisetcommitratio start >/dev/null || fail
[[ -f $tmp_overcommit_ratio ]] &&[[ $(<$tmp_overcommit_ratio) == 90 ]] || fail
test_finish "$t"

t="When memtotal=100 and 200MB is reserved, the commit ratio should be set to 25, and a warning should be printed"
test_start "$t"
echo 200 > "$tmp_memreserve_dir/test1"
MEMTOTAL_KB=102400 $nisetcommitratio start >/dev/null 2>"$stderr" || fail
[[ -f $tmp_overcommit_ratio ]] && \
	(( $(<$tmp_overcommit_ratio) == 25 && $(<$tmp_overcommit_ratio) > 0 )) \
	|| fail
[[ $(<$stderr) ]] || fail
test_finish "$t"

t="When memtotal=0 and 10MB is reserved, the commit ratio should not be changed, and a warning should be printed"
test_start "$t"
echo 10 > "$tmp_memreserve_dir/test1"
MEMTOTAL_KB=0 $nisetcommitratio start >/dev/null 2>"$stderr" || fail
verbose "stderr: $(<$stderr)"
[[ -f $tmp_overcommit_ratio ]] && fail
[[ $(<$stderr) ]] || fail
test_finish "$t"

t="When memtotal=64GB and 100MB is reserved, the commit ratio should be set to 99"
test_start "$t"
echo 100 > "$tmp_memreserve_dir/test1"
MEMTOTAL_KB=67108864 $nisetcommitratio start >/dev/null 2>"$stderr" || fail
[[ -f $tmp_overcommit_ratio ]] &&[[ $(<$tmp_overcommit_ratio) == 99 ]] || fail
test_finish "$t"
