#!/bin/bash
set -e
set -u
set -o pipefail

trap 'exitCode="$?"; set +e; echo "FAIL $0"; exit "$exitCode"' EXIT

echo "check that niopendisks runs before mountall and sysfs"
ls -l "/etc/rcS.d/S00niopendisks"
ls -l "/etc/rcS.d/S02mountall.sh"
ls -l "/etc/rcS.d/S02sysfs.sh"
echo "OK"

echo "PASS $0"
trap - EXIT
