#!/bin/bash

LOG_DIR="/var/local/ptest-results/kernel-test-nohz"

# redirect all stderr to stdout to maintain ordering of output
exec 2>&1

# default test parameters based on PXIe-8880 numbers
MAX_LATENCY=6000
P3NINES=250
P4NINES=3000

# load device specific test parameters
DEVICE=$(fw_printenv DeviceDesc | sed 's/DeviceDesc=//')
if source "./$DEVICE.conf" 2>/dev/null ; then
    echo "test parameters loaded from $DEVICE.conf"
else
    echo "warning: $DEVICE.conf not found; using default test parameters"
fi

# disable tracing
echo 0 > "/sys/kernel/debug/tracing/tracing_on"

# move kernel worqueue threads to CPU 0
for file in `find /sys/devices/virtual/workqueue -name "cpumask"`; do
    echo 1 > "$file" 2>/dev/null
done

# delay the vmstat timer far away
sysctl vm.stat_interval=999

# create local results directory
mkdir -p "$LOG_DIR"

# start background scheduler load
hackbench -l 36000000 -g 10 > /dev/null &

# run test
./nohz_test --max="$MAX_LATENCY" --p3nines="$P3NINES" --p4nines="$P4NINES" --duration=24h | tee "$LOG_DIR/output-`date +'%Y_%m_%d-%H_%M_%S'`.log"
RESULT=${PIPESTATUS[0]}

# cleanup
killall -INT hackbench > /dev/null

exit $RESULT
