#!/bin/sh

IP_RESET_FILE="/dev/nirtfeatures/ip_reset"

IP_RESET_REQUESTED=""
if [ -e "$IP_RESET_FILE" ]; then
	grep -q '1' $IP_RESET_FILE && IP_RESET_REQUESTED="y"
else
	[ "${VERBOSE}" = "yes" ] && echo "Unable to find ip_reset at normal spot."
fi

if [ "$IP_RESET_REQUESTED" == "y" ]; then
	mkdir -p /tmp/ip_reset_dir
	ninetcfgutil pulldefault -d /tmp/ip_reset_dir -g primary -g secondary
	rm -rf /tmp/ip_reset_dir
fi
