#!/bin/bash

# The purpose of this script is to sync the CPLD NOFPGA autoload setting with
# values stored in various config files.

NOFPGA_CPLD=/sys/bus/acpi/devices/NIC775D\:00/no_fpga_sw
NOFPGA_FILE=/etc/nofpga

if [ -f $NOFPGA_CPLD ]; then
	if [ -f $NOFPGA_FILE ]; then
		echo 1 > $NOFPGA_CPLD
	else
		echo 0 > $NOFPGA_CPLD
	fi
fi
