#! /bin/sh

if [ `/sbin/fw_printenv -n BIOSBootMode` = "legacy" ]; then
	exit 0
fi

case "$1" in
	start)
		;;

	stop)
		# compare the value save in grubenv with the one in the BIOS. If they differ, set the BIOS variable
		echo "Setting ConsoleOutEnable"
		grubConsoleOutEnableTmp=`fw_printenv -n consoleoutenable 2> /dev/null | tr '[:upper:]' '[:lower:]'`
		if [ "$grubConsoleOutEnableTmp" = "true" ]; then
			grubConsoleOutEnable=1
		else
			grubConsoleOutEnable=0
		fi

		efiConsoleOutEnable=`fw_printenv -n BootFirmwareConsoleOutEnable 2> /dev/null`

		if [ -n "$efiConsoleOutEnable" ]; then
			if [ ! "$grubConsoleOutEnable" = "$efiConsoleOutEnable" ]; then
				fw_setenv BootFirmwareConsoleOutEnable $grubConsoleOutEnable
			fi
		fi
		;;
esac
