#!/bin/bash
### BEGIN INIT INFO
# Provides:          ptest-runner
# Required-Start:    $all
# Required-Stop:
# Default-Start:     5
# Default-Stop:
# Short-Description: Run NILRT ptests
# Description:       Parses the kernel command line for a 'ptest' keyword and,
#                    if it is found, starts the ptest-runner test suite and logs
#                    output to /tmp.
### END INIT INFO

ARG_PTEST="ptest"
CMD_PTEST="ptest-runner"
MATCH_PTEST="\(\s\+\|^\)${ARG_PTEST}\($\|\s\+\)"

case "$1" in
	"" | "start" | "restart" | "force-reload")
		if [ "$2" != "--force" ]; then
			$(grep -q -e "${MATCH_PTEST}" /proc/cmdline) || exit 1
		fi

		echo "<tchamber>PTEST RUN START</tchamber>" > /dev/console
		script -c "$CMD_PTEST" --flush /tmp/${CMD_PTEST}.log
		echo "<tchamber>PTEST RUN COMPLETE</tchamber>" > /dev/console
		;;
	"stop" | "status")
		exit 3
		;;
	*)
		exit 2
		;;
esac

exit 0
