#!/bin/sh
### BEGIN INIT INFO
# Provides:          usbguard
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: USB device authorization policy framework
# Description:        The USBGuard software framework helps to protect your computer against rogue
#                     USB devices (a.k.a. BadUSB) by implementing basic allow- and blocklisting
#                     capabilities based on device attributes.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

NAME=usbguard
DAEMON=/usr/sbin/usbguard-daemon
DESC="Usbguard daemon"
PIDFILE=/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
CONFIG_FILE=/etc/usbguard/usbguard-daemon.conf
LOG_DIR=/var/log/usbguard

# Ensure log directory exists
if [ ! -d "$LOG_DIR" ]; then
    mkdir -p "$LOG_DIR"
fi

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Exit if the configuration file does not exist
[ -f "$CONFIG_FILE" ] || exit 0

. /etc/default/rcS

. /etc/init.d/functions

if [ -f /lib/lsb/init-functions ]
then
    . /lib/lsb/init-functions
else
    log_use_fancy_output () {
        if  [ -t 1 ] &&
        [ "x${TERM:-}" != "x" ] &&
        [ "x${TERM:-}" != "xdumb" ]
        then
            [ -z $FANCYTTY ] && return 0 || true
        else
            return 1
        fi
        case "$FANCYTTY" in
            1|Y|yes|true)   true;;
            *)              false;;
        esac
    }

    # int log_begin_message (char *message)
    log_begin_msg () {
        if [ -z "$1" ]; then
            return 1
        fi
        echo " * $@"
    }

    # int log_end_message (int exitstatus)
    log_end_msg () {

    # If no arguments were passed, return
        [ -z "$1" ] && return 1

    # Only do the fancy stuff if we have an appropriate terminal
    # and if /usr is already mounted
        TPUT=/usr/bin/tput
        EXPR=/usr/bin/expr
        if [ -x $TPUT ] && [ -x $EXPR ] && $TPUT hpa 60 >/dev/null 2>&1; then
            COLS=`$TPUT cols`
            if [ -n "$COLS" ]; then
                COL=`$EXPR $COLS - 7`
            else
                COL=73
            fi
            UP=`$TPUT cuu1`
            END=`$TPUT hpa $COL`
            START=`$TPUT hpa 0`
            RED=`$TPUT setaf 1`
            NORMAL=`$TPUT op`
            if [ $1 -eq 0 ]; then
                echo "$UP$END[ ok ]"
            else
                echo -e "$UP$START $RED*$NORMAL$END[${RED}fail${NORMAL}]"
            fi
        else
            if [ $1 -eq 0 ]; then
                echo "   ...done."
            else
                echo "   ...fail!"
            fi
        fi
        return $1
    }

    log_warning_msg () {
        if log_use_fancy_output; then
            YELLOW=`$TPUT setaf 3`
            NORMAL=`$TPUT op`
            echo "$YELLOW*$NORMAL $@"
        else
            echo "$@"
        fi
    }

    log_failure_msg () {
        if log_use_fancy_output; then
            RED=`$TPUT setaf 1`
            NORMAL=`$TPUT op`
            echo " $RED*$NORMAL $@" || true
        else
            echo " * $@" || true
        fi
    }

fi

usbguard_daemon_start()
{
    if [ -f "$PIDFILE" ]; then
        log_failure_msg "$DESC is running already."
        exit 1
    fi

    start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- -f -s -c $CONFIG_FILE
}

usbguard_daemon_stop()
{
	if [ -f "$PIDFILE" ]; then
		start-stop-daemon --stop --signal INT --pidfile $PIDFILE
		rm -f $PIDFILE
	fi
}

usbguard_daemon_status() {
	if [ -f $PIDFILE ]; then
		status -p $PIDFILE $DAEMON
	else
		status $DAEMON
	fi
}

case "$1" in
  start)
  	log_begin_msg "Starting ${DESC}"
	usbguard_daemon_start
	log_end_msg $?
	;;
  stop)
  	log_begin_msg "Stopping ${DESC}"
	usbguard_daemon_stop
	log_end_msg $?
	;;
  status)
  	usbguard_daemon_status
	;;
  restart|reload|force-reload)
  	log_begin_msg "Restarting ${DESC}"
	usbguard_daemon_stop
	usbguard_daemon_start
	log_end_msg $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}"
	exit 1
	;;
esac
