SUMMARY = "NI gRPC Device Server"
DESCRIPTION = "gRPC server providing remote access to NI device driver APIs."
HOMEPAGE = "https://github.com/ni/grpc-device"
SECTION = "base"
LICENSE = "MIT & Apache-2.0"
LIC_FILES_CHKSUM = "\
	file://LICENSE;md5=f7f2c0314387ea903bd40965abfad353 \
	file://ThirdPartyNotices.txt;md5=57283cec49f9773bb10bac48da2e56df \
"


DEPENDS += "\
	googletest-native \
	grpc \
	grpc-native \
	ni-grpc-sideband \
	nlohmann-json-native \
	protobuf \
	protobuf-native \
	python3-grpcio-tools-native \
	python3-mako-native \
	python3-native \
	python3-schema-native \
	utf8cpp-native \
"

PV = "2.17.0+git${SRCPV}"


SRC_URI = "\
	git://github.com/ni/grpc-device.git;name=grpc-device;branch=main;protocol=https \
	git://github.com/ni/ni-apis.git;name=ni-apis;protocol=https;nobranch=1;destsuffix=${S}/third_party/ni-apis \
	file://ptest \
"

SRCREV_grpc-device = "a1830a7ac5274c34f955046cdc719fbf1648ab90"
SRCREV_ni-apis = "00356cce09dd61d15f6799a87c27460a7d7a0c24"
SRCREV_FORMAT = "grpc-device"


inherit cmake python3native

EXTRA_OECMAKE += "\
	-DCMAKE_CROSSCOMPILING=True \
	-DCMAKE_BUILD_TYPE=Release \
	-DUSE_SUBMODULE_LIBS=OFF \
	-DUSE_PYTHON_VIRTUALENV=OFF \
"
OECMAKE_TARGET_COMPILE = "ni_grpc_device_server"
OECMAKE_GENERATOR = "Unix Makefiles"

# Don't error on deprecated declarations warnings
CXXFLAGS:append = " -Wno-error=deprecated-declarations"

# When USE_SUBMODULE_LIBS=OFF the protoc invocations for driver protos only
# have imports/protobuf/ on their -I path. Copy the ni-apis proto files there
# so they can be found without patching CMakeLists.txt.
# Also add the missing absl_log_* deps (needed by waveform.pb.cc).
do_configure:prepend() {
    cp ${S}/third_party/ni-apis/ni/grpcdevice/v1/session.proto \
        ${S}/imports/protobuf/
    install -d ${S}/imports/protobuf/ni/protobuf/types
    cp ${S}/third_party/ni-apis/ni/protobuf/types/precision_timestamp.proto \
        ${S}/imports/protobuf/ni/protobuf/types/
    cp ${S}/third_party/ni-apis/ni/protobuf/types/waveform.proto \
        ${S}/imports/protobuf/ni/protobuf/types/

    # Add find_library calls for absl_log_* libs after the existing _ABSEIL_SYNC line
    sed -i 's|find_library(_ABSEIL_SYNC absl_synchronization REQUIRED)|find_library(_ABSEIL_SYNC absl_synchronization REQUIRED)\n  find_library(_ABSEIL_LOG_MSG absl_log_internal_message REQUIRED)\n  find_library(_ABSEIL_LOG_NULLGUARD absl_log_internal_nullguard REQUIRED)\n  find_library(_ABSEIL_LOG_GLOBALS absl_log_internal_globals REQUIRED)\n  find_library(_ABSEIL_LOG_CONDITIONS absl_log_internal_conditions REQUIRED)\n  find_library(_ABSEIL_LOG_FORMAT absl_log_internal_format REQUIRED)\n  find_library(_ABSEIL_LOG_PROTO absl_log_internal_proto REQUIRED)\n  find_library(_ABSEIL_LOG_SINK_SET absl_log_internal_log_sink_set REQUIRED)\n  find_library(_ABSEIL_LOG_SINK absl_log_sink REQUIRED)\n  find_library(_ABSEIL_LOG_ENTRY absl_log_entry REQUIRED)|' \
        ${S}/CMakeLists.txt

    # Add all absl log libs to server_lib_deps (after nlohmann_json line)
    sed -i 's|  nlohmann_json::nlohmann_json|  nlohmann_json::nlohmann_json\n  ${_ABSEIL_LOG_MSG}\n  ${_ABSEIL_LOG_NULLGUARD}\n  ${_ABSEIL_LOG_GLOBALS}\n  ${_ABSEIL_LOG_CONDITIONS}\n  ${_ABSEIL_LOG_FORMAT}\n  ${_ABSEIL_LOG_PROTO}\n  ${_ABSEIL_LOG_SINK_SET}\n  ${_ABSEIL_LOG_SINK}\n  ${_ABSEIL_LOG_ENTRY}|' \
        ${S}/CMakeLists.txt
}


#inherit ptest
#
#BUILD_PTEST = "${B}/ptest"
#RDEPENDS:${PN}-ptest += "\
#	${PN} \
#	bash \
#	python3-grpcio \
#"
#
#do_compile_ptest:append () {
#	install -d ${BUILD_PTEST}
#	python3 -m grpc_tools.protoc \
#		-I${S}/source/protobuf \
#		--python_out=${BUILD_PTEST} \
#		--grpc_python_out=${BUILD_PTEST} \
#		${S}/source/protobuf/session.proto
#}
#
#do_install_ptest:append () {
#	install -d ${D}${PTEST_PATH}
#	install -m 0755 ${WORKDIR}/ptest/run-ptest ${D}${PTEST_PATH}/
#
#	install -m 0644 ${S}/examples/session/enumerate-device.py ${D}${PTEST_PATH}/
#
#	# These files are generated by the do_compile_ptest task.
#	install -m 0644 ${BUILD_PTEST}/session_pb2_grpc.py ${D}${PTEST_PATH}/
#	install -m 0644 ${BUILD_PTEST}/session_pb2.py ${D}${PTEST_PATH}/
#}


serverdir = "${D}${libdir}/${BPN}"
# grpc-device does not provide an 'install' target (yet); so overwrite the whole
# of do_install, to keep cmake from building anything further.
do_install () {
	# install server components
	install -d ${serverdir}
	install --mode=0755 ${B}/ni_grpc_device_server    ${serverdir}
	install --mode=0644 ${B}/server_config.json       ${serverdir}/server_config.json.example
	install --mode=0644 ${B}/server_capabilities.json ${serverdir}

	# package .proto files for use by developers
	install -d ${D}${datadir}/${BPN}
	install --mode=0644 ${S}/generated/**/*.proto     ${D}${datadir}/${BPN}
	install --mode=0644 ${S}/imports/protobuf/*.proto ${D}${datadir}/${BPN}

	# install example files
	install -d ${D}${datadir}/${BPN}
	cp -r ${S}/examples ${D}${datadir}/${BPN}
}

PACKAGE_BEFORE_PN = "${PN}-examples"

# ${PN}
do_install:append () {
	install -d ${D}${sysconfdir}/nitlsconfig/server.d
	install --mode=0644 ${S}/source/config/ni-grpc-device.conf.yml \
		${D}${sysconfdir}/nitlsconfig/server.d/ni-grpc-device.conf.yml
	install --mode=0644 ${S}/source/config/ni-grpc-device.caps.yml \
		${D}${sysconfdir}/nitlsconfig/server.d/ni-grpc-device.caps.yml
}

FILES:${PN} += "\
	${sysconfdir}/nitlsconfig/server.d/ni-grpc-device.conf.yml \
	${sysconfdir}/nitlsconfig/server.d/ni-grpc-device.caps.yml \
"
RDEPENDS:${PN} += "\
	grpc \
	ni-grpc-sideband \
	protobuf \
"

# ${PN}-dev
FILES:${PN}-dev:append = "${datadir}/${BPN}/*.proto"
RDEPENDS:${PN}-dev:append = "\
	grpc-dev \
"

# ${PN}-examples
FILES:${PN}-examples = "${datadir}/${BPN}/examples"
RDEPENDS:${PN}-examples = "\
	python3 \
"
