#!/bin/bash

if [ -e /ni_provisioning.common ]; then
    source /ni_provisioning.common
else
    printf "\n***Error: File ni_provisioning.common not found!\n"
    printf "PROVISIONING FAILED!"
    exit 1
fi

early_setup

PROVISION_TARGET="n"
RESET_MINIMAL_IMAGE="n"
CONTINUE="n"
if [[ $restore == "provision" ]]; then
    echo
    echo "NI Real-Time Recovery."
    if [ "$(dmidecode | grep -c "DMI type 160")" -eq 0 ]; then
        print_warning "This target is not supported!"
        echo
        read -p "Do you want to continue?[y/N]" CONTINUE
        if [[ ${CONTINUE,,} != "y" ]]; then
            cleanup_and_exit 0
        fi
    fi
    echo
    echo "The boot style is $BOOT_STYLE"
    echo
    echo "Continuing will partition, format and install minimal image to the target."
    echo
    read -p "Do you want to continue?[y/N]" PROVISION_TARGET
    if [[ ${PROVISION_TARGET,,} == "y" ]]; then
        provision_target usb
    fi
elif [[ $restore == "migrate" || $restore == "backward-migrate" ]]; then
    AUTO_REBOOT=1
    provision_target onboard $restore
elif [[ $restore == "auto-restore" ]]; then
    restore_minimal_image
else
    echo
    echo "NI Real-Time Restore."
    echo
    echo "Continuing will format the nilrt partition and will install minimal image."
    echo
    read -p "Do you want to continue?[y/N]" RESTORE_MINIMAL_IMAGE
    if [[ ${RESTORE_MINIMAL_IMAGE,,} == "y" ]]; then
        restore_minimal_image
    fi
fi

cleanup_and_exit 0
