#!/bin/bash

function setup_container_load()
{
   docker pull hello-world
}

function start_container_load()
{
   while true; do
      docker run hello-world > /dev/null
      docker container prune -f > /dev/null
   done
}
