#!/bin/bash
set -e
source "/usr/lib/nilrtdiskcrypt.common"

function print_usage_and_die () {
    local message="$1"
    cat >&2 <<ENDHELP
ERROR: $message

Usage: $0 [ -d devNode ... ]
 Unmounts and closes the specified devices
ENDHELP
    exit 1
}

# get args
devNodes=""

while getopts "d:" opt; do
    case "$opt" in
    d )  devNodes="$devNodes $OPTARG" ;;
    \?)  print_usage_and_die "Invalid arg" ;;
    esac
done
shift $(($OPTIND - 1))

[ -n "$devNodes" ] || print_usage_and_die "Must specify at least one device"

status "Init"
take_lock
cd_to_empty

status "Unmount mapper devices"
for devNode in $devNodes; do
    mapperPath="`get_mapper_path "$devNode"`"
    if mount | grep -q "^$mapperPath "; then
        status "Unmount mapperPath=$mapperPath"
        umount "$mapperPath"
    else
        status "SKIP unmount mapperPath=$mapperPath (not mounted)"
    fi
done

status "luksClose devices"
for devNode in $devNodes; do
    mapperPath="`get_mapper_path "$devNode"`"
    if [ -e "$mapperPath" ]; then
        status "luksClose mapperPath=$mapperPath"
        do_silently cryptsetup luksClose "$mapperPath"
    else
        status "SKIP luksClose mapperPath=$mapperPath (not open)"
    fi
done

status "Sanity check: Ensure specified devices are not mounted or open"
for devNode in $devNodes; do
    sanity_check_luks_volume_closed "$devNode"
done

status "SUCCESS"
