#!/bin/bash
set -e
source "/usr/lib/nilrtdiskcrypt.common"

function print_usage_and_die () {
    local message="$1"
    cat >&2 <<ENDHELP
ERROR: $message

Usage: $0 [ -k keySlotNumber ...]
Removes the keys in specific slots from TPM.
ENDHELP
    exit 1
}

# get args
keySlotNumbers=""

while getopts "k:" opt; do
    case "$opt" in
    k )  keySlotNumbers="$keySlotNumbers $OPTARG" ;;
    \?)  print_usage_and_die "Invalid arg" ;;
    esac
done
shift $(($OPTIND - 1))

[ -n "$keySlotNumbers" ] || print_usage_and_die "Must specify at least one key slot"

status "Init"
take_lock
cd_to_empty
init_work_dir

status "Clear existing keys in TPM"
for ksNumb in $keySlotNumbers; do
    ksHandle="`get_key_slot_handle "$ksNumb"`"
    nvrelease_ifdefined "$ksHandle"
done

status "SUCCESS"
