#!/bin/bash
set -e
source "/usr/lib/nilrtdiskcrypt.common"

status "Init"
take_lock
cd_to_empty

if tpm2_pcrlist -L "$TPM_ALG_SHA256:11" | grep -q '^PCR_11:0\+$'; then
    tpm2_pcrextend "11:$TPM_ALG_SHA256=$(printf "$KEY_MAGIC" | sha256sum | cut -d' ' -f1)"
else
    warn "Unsealing is already disabled."
fi

status "SUCCESS"
