#!/bin/bash
set -e
source "/usr/lib/nilrtdiskcrypt.common"

function print_usage_and_die () {
    local message="$1"
    echo >&2 "ERROR: $message"
    echo >&2 ""
    echo >&2 "Usage: $0 [ -u unsealedKeySlotNumber ...]"
    echo >&2 " Reads and reseals disk key in specified slots"
    exit 1
}

# get args
unsealedKeySlotNumbers=""

while getopts "u:" opt; do
    case "$opt" in
    u )  unsealedKeySlotNumbers="$unsealedKeySlotNumbers $OPTARG" ;;
    \?)  print_usage_and_die "Invalid arg" ;;
    esac
done
shift $(($OPTIND - 1))

[ -n "$unsealedKeySlotNumbers" ] || print_usage_and_die "Must specify at least one key slot"

status "Init"
take_lock
cd_to_empty
init_work_dir

for ksNumb in $unsealedKeySlotNumbers; do
    ksHandle="`get_key_slot_handle "$ksNumb"`"
    reseal_disk_key "$ksHandle"
    init_work_dir
done

status "Remove key"
clear_work_dir

status "SUCCESS"
