#!/bin/bash
set -e
source "/usr/lib/nilrtdiskcrypt.common"

function print_usage_and_die () {
    local message="$1"
    cat >&2 <<ENDHELP
ERROR: $message

Usage: $0 [-c | -d] [-P password]
 -c Clears existing lockout
 -d Disables dictionary lockout functionality and minimally sets lockout
    recovery time to 1 second.
 -P The lockout password. Must to be specified in order to clear or
    disable lockout, if configured
ENDHELP
    exit 1
}

# get args
mode=""
password=""
use_password=false

while getopts "cdP:" opt; do
    case "$opt" in
    c )  [ -z "$mode" ] && mode="clear" || print_usage_and_die "Cannot set multiple modes" ;;
    d )  [ -z "$mode" ] && mode="disable" || print_usage_and_die "Cannot set multiple modes" ;;
    P )  if $use_password; then
            print_usage_and_die "Cannot specify more than one password"
         else
            password="$OPTARG"
            use_password=true
         fi
         ;;
    esac
done
shift $(($OPTIND - 1))

[ -n "$mode" ] || print_usage_and_die "Must specify a mode: -c (clear) or -d (disable)"

password_param=""
if $use_password; then
    password_param="--lockout-passwd '$password'"
    status "Using password_param=$password_param"
fi

status "Init"
take_lock
cd_to_empty
init_work_dir

if [ "$mode" == "clear" ]; then
    status "Clearing dictionary lockout"
    if ! tpm2_dictionarylockout $password_param --clear-lockout; then
        error "Failed to clear dictionary lockout"
    fi
fi

if [ "$mode" == "disable" ]; then
    # From https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf section 25.3
    # ----------
    # If newRecoveryTime is zero, then DA protection is disabled.
    #  Authorizations are checked but authorization failures will
    #  not cause the TPM to enter lockout.
    # If newMaxTries is zero, the TPM will be in lockout and use
    #  of DA protected entities will be disabled.
    # If lockoutRecovery is zero, then the recovery interval is
    #  _TPM_Init() followed by TPM2_Startup().
    # ----------

    status "Disabling dictionary lockout"
    if ! tpm2_dictionarylockout $password_param --setup-parameters --max-tries 1 --recovery-time 0 --lockout-recovery-time 1; then
        error "Failed to disable dictionary lockout"
    fi
fi

status "SUCCESS"
