#!/bin/bash
set -e
source "/usr/lib/nilrtdiskcrypt.common"

status "Init"
take_lock
cd_to_empty

tpm2_pcrextend "11:$TPM_ALG_SHA256=$(printf "$KEY_MAGIC" | sha256sum | cut -d' ' -f1)"

if tpm2_pcrlist -L "$TPM_ALG_SHA256:11" | grep -q '^PCR_11:0\+$'; then
    error "Failed to extend PCR 11"
fi

status "SUCCESS"
