#!/bin/bash
set -e
VERBOSE=${VERBOSE:-1}
source "/usr/lib/nilrtdiskcrypt.common"

status "TEST: Init"
take_lock
cd_to_empty

status "TEST: Release key slots"
init_work_dir
nvrelease_ifdefined "$KEYSLOT00_NVRAMHANDLE"
nvrelease_ifdefined "$KEYSLOT01_NVRAMHANDLE"
nvread_file_ifdefined "EmptyFile0" "$KEYSLOT00_NVRAMHANDLE"
nvread_file_ifdefined "EmptyFile1" "$KEYSLOT01_NVRAMHANDLE"
[ -s "EmptyFile0" ] && error "EmptyFile0 not empty"
[ -s "EmptyFile1" ] && error "EmptyFile1 not empty"

status "TEST: define keys slots"
init_work_dir
nvdefine "$KEYSLOT00_NVRAMHANDLE" "510" "$KEY_SLOT_ATTRIBUTES"
nvdefine "$KEYSLOT01_NVRAMHANDLE" "1024" "$KEY_SLOT_ATTRIBUTES"
dd if="/dev/urandom" of="$WORK_DIR/garbage-510.urandom" bs=510 count=1
dd if="/dev/urandom" of="$WORK_DIR/garbage-1024.urandom" bs=1024 count=1
nvwrite_file "garbage-510.urandom" "$KEYSLOT00_NVRAMHANDLE"
nvwrite_file "garbage-1024.urandom" "$KEYSLOT01_NVRAMHANDLE"

status "TEST: provision keys"
init_work_dir
create_sealed_disk_key "$DEFAULT_KEY_SEALING_PCR_SET"
nvrelease_ifdefined "$KEYSLOT00_NVRAMHANDLE"
nvrelease_ifdefined "$KEYSLOT01_NVRAMHANDLE"
nvdefine "$KEYSLOT00_NVRAMHANDLE" "`stat -c %s "$WORK_DIR/key.sealed.gz"`" "$KEY_SLOT_ATTRIBUTES"
nvdefine "$KEYSLOT01_NVRAMHANDLE" "`stat -c %s "$WORK_DIR/key.unsealed.gz"`" "$KEY_SLOT_ATTRIBUTES"
nvwrite_file "key.sealed.gz" "$KEYSLOT00_NVRAMHANDLE"
nvwrite_file "key.unsealed.gz" "$KEYSLOT01_NVRAMHANDLE"

status "TEST: read functions"
init_work_dir
nvread_file "key0a" "$KEYSLOT00_NVRAMHANDLE"
nvread_file_ifdefined "key0b" "$KEYSLOT00_NVRAMHANDLE"
nvread_file "key1a" "$KEYSLOT01_NVRAMHANDLE"
nvread_file_ifdefined "key1b" "$KEYSLOT01_NVRAMHANDLE"
cmp "$WORK_DIR/key0a" "$WORK_DIR/key0b" || error "nvread_file and nvread_file_ifdefined mismatch (key slot 0)"
cmp "$WORK_DIR/key1a" "$WORK_DIR/key1b" || error "nvread_file and nvread_file_ifdefined mismatch (key slot 1)"

status "TEST: read back safemode key"
init_work_dir
download_disk_key "$KEYSLOT00_NVRAMHANDLE"

status "TEST: read back runmode key"
init_work_dir
nvread_file "key.out.gz" "$KEYSLOT01_NVRAMHANDLE"
unpack_key "key.out.gz" "key.out"
has_unsealed_key || error "Runmode key should be unsealed after provisioning"
has_sealed_key   && error "Found sealed runmode key after provisioning"

status "TEST: seal runmode key"
create_sealing_policy "$DEFAULT_KEY_SEALING_PCR_SET"
write_sealing_pcr_set "$DEFAULT_KEY_SEALING_PCR_SET"
seal_key
pack_sealed_key
nvrelease_ifdefined "$KEYSLOT01_NVRAMHANDLE"
nvdefine "$KEYSLOT01_NVRAMHANDLE" "`stat -c %s "$WORK_DIR/key.sealed.gz"`" "$KEY_SLOT_ATTRIBUTES"
nvwrite_file "key.sealed.gz" "$KEYSLOT01_NVRAMHANDLE"

status "TEST: read back re-sealed runmode key"
init_work_dir
download_disk_key "$KEYSLOT01_NVRAMHANDLE"

status "TEST PASSED"
