#!/bin/bash
set -e
source "/usr/lib/nilrtdiskcrypt.common"

function print_usage_and_die () {
    local message="$1"
    cat >&2 <<ENDHELP
ERROR: $message

Usage: $0 [ -d devNode ...]
 Exits with 0 if all specified devNodes may be opened.
 Exits non-zero otherwise with reason on stderr.
ENDHELP
    exit 1
}

# get args
devNodes=""

while getopts "d:" opt; do
    case "$opt" in
    d )  devNodes="$devNodes $OPTARG" ;;
    \?)  print_usage_and_die "Invalid arg" ;;
    esac
done
shift $(($OPTIND - 1))

[[ -n "$devNodes" && ! -z "${devNodes// }" ]] || print_usage_and_die "Must specify at least one device"

exitCode=0
for devNode in $devNodes; do
    if ! cryptsetup isLuks "$devNode"; then
        echo >&2 "$devNode is not encrypted (not a luks device)"
        exitCode=1
    fi
done

exit $exitCode
