#!/bin/bash
#
# Copyright (C) 2013-2023 National Instruments
# Copyright (C) 2023-2026 Emerson
#
# For grub and u-boot targets, format the rootfs and the config volumes and
# delete the runmode kernel.

# Bail out on first error
set -E -o errexit


# ==============================================================================
# CONSTANTS
# ==============================================================================

ARCH=$(uname -m)

PREFIX=$(realpath "$(dirname "$(readlink -f "$0")")/..")
libdir="$PREFIX/lib/ni-systemformat"

declare -r BASENAME=${0##*/}

ACCTINFO_TMP=/tmp/acctinfo

# Device partition discovery
if [ "$ARCH" = "x86_64" ]; then
	CONFIGFS_DEV=/dev/disk/by-label/niconfig
	ROOTFS_DEV=/dev/disk/by-label/nirootfs
fi
CONFIG_MOUNT_POINT="/etc/natinst/share"
ROOTFS_MOUNT_POINT="/mnt/userfs"
TARGETINFO_PATH="$CONFIG_MOUNT_POINT/targetinfo.ini"

# Network config
NETCFG_MODE=bypass
NETCFG_TMP=/tmp/netconfig.$$
NINETCFGUTIL=/usr/local/natinst/bin/ninetcfgutil


# ==============================================================================
# IMPORTS
# ==============================================================================

source "$libdir"/exit_codes.sh   || exit
	# EXITCODES
source "$libdir"/util.sh  || exit ${EXITCODES[IMPORT_ERROR]}
	# die, handle_err, with_retry, install_default_err_handler
source "$libdir"/usage.sh || exit ${EXITCODES[IMPORT_ERROR]}
	# parse_args, validate_args

# include common utilities
if [ -e /etc/init.d/mountutils ]; then
	source /etc/init.d/mountutils
fi


# ==============================================================================
# FUNCTIONS
# ==============================================================================

supported_fstypes()
{
	hash /usr/sbin/ubiformat 2>/dev/null && [ "$ARCH" = "armv7l" ] && echo -n "ubifs," || true
	hash /sbin/mkfs.ext4 2>/dev/null && [ "$ARCH" = "x86_64" ] && echo -n "ext4," || true
}

# Find the filesystem type of the root partition (or volume)
print_root_fstype()
{
	if [ "$OSMODE" != runmode ]; then
		grep " $ROOTFS_MOUNT_POINT " /proc/mounts | awk '{print $3}'
	else
		# regarding skipping rootfs, see "What is rootfs?" at
		# https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt
		grep " / " /proc/mounts | awk '{if ($3 != "rootfs") print $3}'
	fi
}

# Find the filesystem type of the config partition (or volume)
print_config_fstype()
{
	grep " $CONFIG_MOUNT_POINT " /proc/mounts | awk '{print $3}'
}

# Format the rootfs volume
# $1: filesystem to use (currently "ubifs" or "ext4")
# $2: root device (defaults to $ROOTFS_DEV, only works for x86_64 on ARM is ignored)
format_rootfs()
{
	# remove Zynq kernel
	rm -f /boot/linux_runmode.itb

	# remove any old kernel-dev files which were deposited in the /boot partition
	rm -f /boot/Module.symvers-*
	rm -f /boot/config-*
	rm -f /boot/System.map-*

	# remove x64 kernel
	if [ -e /boot/runmode  ]; then
		rm -R /boot/runmode
		mkdir /boot/runmode
	fi

	# fstype is validated before calling format_rootfs
	case "$1" in
	  ubifs)
		local partition_label="root"
		local volume_number="0"
		local volume_label="rootfs"
		format_ubi_volume "$partition_label" "$volume_number" "$volume_label"
		;;
	  ext4)
		local volume_label="nirootfs"
		local options=""
		mkfs.ext4 -q -F -L $volume_label $options ${2:-$ROOTFS_DEV}
		;;
	esac
}

# Format the config volume
# $1: filesystem to use (currently "ubifs" or "ext4")
# $2: configfs device (defaults to $CONFIGFS_DEV, only works for x86_64 on ARM is ignored)
format_config()
{
	# fstype is validated before calling format_config
	case "$1" in
	  ubifs)
		local partition_label="boot-config"
		local volume_number="3"
		local volume_label="config"
		format_ubi_volume "$partition_label" "$volume_number" "$volume_label"
		;;
	  ext4)
		local volume_label="niconfig"
		local options=""
		mkfs.ext4 -q -F -I 256 -L $volume_label $options ${2:-$CONFIGFS_DEV}
		;;
	esac
}


netconfig_pre()
{
	[[ $NETCFG_MODE == bypass || $NETCFG_MODE == none ]] && return 0
	rm -rf $NETCFG_TMP
	mkdir -p $NETCFG_TMP
	OPTS=()
	case "$NETCFG_MODE" in
		all) OPTS+=(-g secondary) ;&
		primary) OPTS+=(-g primary) ;;
	esac
	$NINETCFGUTIL save -d $NETCFG_TMP ${OPTS[@]}
}

netconfig_post()
{
	case "$NETCFG_MODE" in
		bypass)
			return 0 ;;
		all|primary)
			$NINETCFGUTIL restore -d $NETCFG_TMP
			rm -rf $NETCFG_TMP
			;;
		none)
			rm -rf $NETCFG_TMP
			mkdir -p $NETCFG_TMP
			$NINETCFGUTIL erase -d $NETCFG_TMP -g primary -g secondary
			rm -rf $NETCFG_TMP
			mkdir -p $NETCFG_TMP
			$NINETCFGUTIL pulldefault -d $NETCFG_TMP -g primary -g secondary
			rm -rf $NETCFG_TMP
			;;
	esac
}

targetinfo_restore()
{
	SUPPORTED_FS=$(supported_fstypes)
	CURRENT_FS=$(print_root_fstype)
	cat >"$TARGETINFO_PATH" <<-EOF
	[FileSystem]
	Current=$CURRENT_FS
	Supported=$SUPPORTED_FS
	EOF
}

# Top-level entry point for reformats. Stop storage-sensitive system services
# prior to the format attempt. Restart services on success if requested, or on
# failure if appropriate.
format_rootfs_or_userfs()
{
	[[ $(supported_fstypes) =~ (^|,)$TYPE(,) ]] || die_with_usage INVALID_FSTYPE "Invalid fstype '$TYPE'"

	/etc/init.d/systemWebServer stop ||:
	/etc/init.d/sshd stop ||:
	/etc/init.d/niauth stop ||:

	# ABORTED_ATTEMPT=yes means something went wrong before we actually reformatted
	# anything: go ahead and restart all services. We set it at the outset,
	# so that any premature failure will set it by default, and unset it once it
	# is no longer applicable.
	ABORTED_ATTEMPT=yes
	local ret=0
	format_rootfs_or_userfs_nosvc || ret=$?
	if (( ! ret )) && [ "$RELAUNCH" = yes ] || [ "$ABORTED_ATTEMPT" = yes ]
	then
		/etc/init.d/niauth start ||:
		/etc/init.d/sshd start ||:
		/etc/init.d/systemWebServer start ||:
	fi
	return $ret
}

# Format operation, assuming all impacted services are shut down. Saves and
# restores system configuration, if necessary.
format_rootfs_or_userfs_nosvc()
{
	netconfig_pre || return $?

	# Backup the shared .shadow file to the tmp dir.
	if [ -f "$CONFIG_MOUNT_POINT/.shadow" ]; then
		trap 'rm -f "$ACCTINFO_TMP/.shadow"' EXIT HUP INT TERM
		mkdir -p "$ACCTINFO_TMP" &&
			cp "$CONFIG_MOUNT_POINT/.shadow" "$ACCTINFO_TMP" ||
			return $?
	fi

	# Backup the restore files to the tmp dir. Do this even if we're only
	# reformatting the configfs, because under some configurations,
	# reformatting the configfs may also trigger reformatting the userfs.
	# (And it doesn't cost us anything to do the copy)
	if [ -e "$ROOTFS_MOUNT_POINT/.restore" ]; then
		mkdir -p /tmp/restore &&
			cp -R "$ROOTFS_MOUNT_POINT"/.restore/* /tmp/restore/ ||
			return $?
	fi

	# If we errored out, either the error was unrecoverable (in which case
	# the rest of this should be skipped), or recoverable (in which case no
	# reformat happened and there is no need to restore configurations)
	format_rootfs_or_userfs_nosvc_noconf || return $?

	local ret=0

	# Move the restore files back to the rootfs. Only do this if the
	# reformat actually happened, i.e. /.restore doesn't exist. In order to
	# make a best-effort attempt at recovery, try to move restore files back
	# to the rootfs (if it exists) even if mountconfig failed.
	if [ -e /tmp/restore -a ! -e "$ROOTFS_MOUNT_POINT/.restore" ] &&
		   mountpoint -q "$ROOTFS_MOUNT_POINT"
	then
		mkdir -p "$ROOTFS_MOUNT_POINT/.restore" &&
			mv /tmp/restore/* "$ROOTFS_MOUNT_POINT/.restore" &&
			rmdir /tmp/restore || (( ret )) || ret=$?
	fi

	# Move the .shadow file back to the configfs.
	if [ -f "$ACCTINFO_TMP/.shadow" -a ! -f "$CONFIG_MOUNT_POINT/.shadow" ] &&
		   mountpoint -q "$CONFIG_MOUNT_POINT"
	then
		mv -f "$ACCTINFO_TMP/.shadow" $CONFIG_MOUNT_POINT &&
			rmdir $ACCTINFO_TMP	|| (( ret )) || ret=$?
	fi

	netconfig_post || (( ret )) || ret=$?
	# targetinfo.ini needs to be restored or it will not be recreated until a reboot into safemode
	targetinfo_restore || (( ret )) || ret=$?
	return $ret
}

# Format operation, assuming all impacted services are shut down, and all
# impacted system configuration has been saved off.
format_rootfs_or_userfs_nosvc_noconf() {
	local ret=0
	if \
		with_retry /etc/init.d/populateconfig stop &&
		with_retry /etc/init.d/mountconfig stop &&
		with_retry /etc/init.d/mountcompatibility stop &&
		with_retry /etc/init.d/mountuserfs stop
	then
		format_rootfs_or_userfs_nomount || (( ret )) || ret=$?
	else
		ret=$?
	fi
	# If we are erroring out unrecoverably, skip the rest of this function
	(( ret )) && ! [ "$ABORTED_ATTEMPT" = yes ] && return $ret

	# configfs needs to be mounted before rootfs otherwise only one
	# *etc/natinst/share will be mounted. (This may be a bug in the mount*
	# initscripts.)
	with_retry /etc/init.d/mountconfig start &&
		with_retry /etc/init.d/populateconfig start || (( ret )) || ret=$?
	with_retry /etc/init.d/mountuserfs start &&
		with_retry /etc/init.d/mountcompatibility start || (( ret )) || ret=$?
	return $ret
}

# Format operation, assuming all impacted mountpoints are unmounted. This is
# what actually does the formatting.
format_rootfs_or_userfs_nomount()
{
	ABORTED_ATTEMPT=	# After this point, failures are unrecoverable

	configfs_dev="$CONFIGFS_DEV"
	rootfs_dev="$ROOTFS_DEV"

	if [ "$VOL" = config ]; then
		format_config "$TYPE" "$configfs_dev"
	else
		format_rootfs "$TYPE" "$rootfs_dev"
	fi
}


# ==============================================================================
# MAIN
# ==============================================================================

install_default_err_handler

# Are we running in safemode, restore mode, or runmode?
if [ -f /etc/natinst/safemode ]; then
	OSMODE=safemode
elif [ -f /etc/natinst/restoremode ]; then
	OSMODE=restore
else
	OSMODE=runmode
fi

case "$(/sbin/runlevel || true)" in
*\ 6|*\ 0) die ILLTIMED "Called during shutdown; aborting." ;;
esac

parse_args "${@}"

case "$MODE" in
	format)
		format_rootfs_or_userfs
	;;
	status)
		if [ "$VOL" = config ]; then
			print_config_fstype
		else
			print_root_fstype
		fi
	;;
	list)
		echo -n $(supported_fstypes)
	;;
esac

exit 0
