#!/bin/bash
#
# Copyright (C) 2013-2023 National Instruments
# Copyright (C) 2023-2026 Emerson
#
# For grub and u-boot targets, format the rootfs and the config volumes and
# delete the runmode kernel.

# Bail out on first error
set -E -u -o errexit


# ==============================================================================
# CONSTANTS
# ==============================================================================

ARCH=$(uname -m)

PREFIX=$(realpath "$(dirname "$(readlink -f "$0")")/..")
libdir="$PREFIX/lib/ni-systemformat"

declare -r BASENAME=${0##*/}


# ==============================================================================
# IMPORTS
# ==============================================================================

source "$libdir"/exit_codes.sh   || exit 8
source "$libdir"/util.sh  || exit ${EXITCODES[IMPORT_ERROR]}
source "$libdir"/usage.sh || exit ${EXITCODES[IMPORT_ERROR]}
source "$libdir"/netconfig.sh || exit ${EXITCODES[IMPORT_ERROR]}

source "$libdir"/format.sh || exit ${EXITCODES[IMPORT_ERROR]}
TARGETINFO_PATH="$CONFIG_MOUNT_POINT/targetinfo.ini"


# include common utilities
if [ -e /etc/init.d/mountutils ]; then
	source /etc/init.d/mountutils
fi


# ==============================================================================
# FUNCTIONS
# ==============================================================================

targetinfo_restore()
{
	SUPPORTED_FS=$(supported_fstypes)
	CURRENT_FS=$(print_root_fstype)
	cat >"$TARGETINFO_PATH" <<-EOF
	[FileSystem]
	Current=$CURRENT_FS
	Supported=$SUPPORTED_FS
	EOF
}


# ==============================================================================
# MAIN
# ==============================================================================

install_default_err_handler

# Are we running in safemode, restore mode, or runmode?
if [ -f /etc/natinst/safemode ]; then
	OSMODE=safemode
elif [ -f /etc/natinst/restoremode ]; then
	OSMODE=restore
else
	OSMODE=runmode
fi

case "$(/sbin/runlevel || true)" in
*\ 6|*\ 0) die ILLTIMED "Called during shutdown; aborting." ;;
esac

parse_args "${@}"


case "$MODE" in
	format)
		format_rootfs_or_userfs
	;;
	status)
		if [ "$VOL" = config ]; then
			print_config_fstype
		else
			print_root_fstype
		fi
	;;
	list)
		echo -n $(supported_fstypes)
	;;
esac


exit ${EXITCODES[OK]}
