#!/bin/sh

# Mounts a "/C" and "/c" directory to support legacy
# projects which may be dumping files here

# Bail out on first error
set -o errexit

[ -d /c -a ! -L /c ] && rmdir /c
ln -sf /mnt/userfs/c /

[ -d /C -a ! -L /C ] && rmdir /C
ln -sf /mnt/userfs/C /

exit 0
