#!/bin/sh

./test_kernel_security.sh
./test_kernel_modules.sh
./test_kernel_cache_info.sh
./test_kernel_mcopy.sh
./test_kernel_cap_support.sh
./test_kernel_ll_route.sh
./test_kernel_hrtimers.sh
./test_kernel_swap_disabled.sh
./test_kernel_dmesg_diff.sh
./test_user_stack_size.sh
./test_i915_firmware.sh
./test_kernel_serial_devices.sh
