#! /bin/sh

PROGRAM_NAME='rtctld'
EXE_PATH='/usr/sbin/rtctld'

# Uncomment these lines if you wish to run rtcrld in a higher priority
# context. This might be necessary in some application where timely
# irq thread configuration is needed.
#CHRT_SCHED_POLICY='f'
#CHRT_SCHED_PRIOR='95'

setsched()
{
    echo -n "Setting $PROGRAM_NAME scheduler priority to $CHRT_SCHED_POLICY:$CHRT_SCHED_PRIOR "
    daemonPid="`pidof "$EXE_PATH"`"

    # root check
    [ -n "`cat "/proc/$daemonPid/status" | egrep '^Uid:(\W+0){4}$'`" ] || echo "WARNING: $PROGRAM_NAME (pid $daemonPid) not running as root user"
    [ -n "`cat "/proc/$daemonPid/status" | egrep '^Gid:(\W+0){4}$'`" ] || echo "WARNING: $PROGRAM_NAME (pid $daemonPid) not running as root group"

    # set scheduler policy
    if chrt -p -"$CHRT_SCHED_POLICY" "$CHRT_SCHED_PRIOR" "$daemonPid" >/dev/null; then
        echo "done"
    else
        echo "ERROR: chrt failed"
        exit 1
    fi
}

startdaemon()
{
    echo -n "Starting $PROGRAM_NAME: "

    if start-stop-daemon --start -x "$EXE_PATH"; then
        echo "done"
    else
        echo "ERROR: start-stop-daemon failed to start"
        exit 1
    fi

    if [ -n "$CHRT_SCHED_POLICY" -a -n "$CHRT_SCHED_PRIOR" ]; then
        setsched
    fi
}

stopdaemon()
{
    echo -n "Stopping $PROGRAM_NAME: "

    if start-stop-daemon --stop --retry 30 -x "$EXE_PATH"; then
        echo "done"
    else
        echo "ERROR: start-stop-daemon failed to stop"
        exit 1
    fi
}

case "$1" in
    start)
        startdaemon
        ;;
    stop)
        stopdaemon
        ;;
    force-reload|restart|reload)
        stopdaemon
        startdaemon
        ;;
    *)
        echo >&2 "Usage: $PROGRAM_NAME {start|stop|restart|reload|force-reload}"
        exit 1
        ;;
esac
