#!/bin/bash
set -euo pipefail
readonly SCRIPT_NAME="rauc-mark-good"

# Finalizes first boot into a new NILRT partition
#  * Migrates old system configuration if present
#  * Marks the current boot good
#  * Cleanups up old system overlay if present
#  * Removes itself from subsequent boots

# close stdin
exec 0<&-

# suppress stdout and stderr if echo fails, so that subsequent
#  tools dont error out when prints occur
if ! echo -n " "; then
    exec 1>/dev/null
fi
if ! echo -n " " 1>&2; then
    exec 2>&1
fi

# prints to kernel log and screen
function error () {
    echo "$SCRIPT_NAME: ERROR: $*" > /dev/kmsg || true
    echo "$SCRIPT_NAME: ERROR: $*" || true
    false
}

function info () {
    echo "$SCRIPT_NAME: $*" > /dev/kmsg || true
    echo "$SCRIPT_NAME: $*" || true
}

function cleanup() {
    local exitCode="$?"

    set +e

    if [ -e "${NIUSER_TMP_MOUNT:-}" ]; then
        umount "$NIUSER_TMP_MOUNT"
        rmdir "$NIUSER_TMP_MOUNT"
    fi

    if [ "$exitCode" != "0" ]; then
        error "exitCode=$exitCode"
    fi

    exit "$exitCode"
}

trap cleanup EXIT

if [ "${1:-}" != "start" ]; then
    error "May only run during startup"
fi

readonly NIUSER_TMP_MOUNT=$(mktemp -d "/var/volatile/niuser-mnt-XXXXXXX")
chmod 0700 "$NIUSER_TMP_MOUNT"
mount -o rw,sync,relatime /dev/niboot/niuser "$NIUSER_TMP_MOUNT"

readonly OLD_OVERLAY="$NIUSER_TMP_MOUNT/overlay.old"
readonly TC_IMAGE="etc/niboot/system-config-image.tgz"

if [ -e "$OLD_OVERLAY/upper/$TC_IMAGE" ]; then
    if transconf restore "$OLD_OVERLAY/upper/$TC_IMAGE"; then
        mv "$OLD_OVERLAY/upper/$TC_IMAGE" "/$TC_IMAGE.restored"
        chown 0:0  "/$TC_IMAGE.restored"
        chmod 0400 "/$TC_IMAGE.restored"

        sync

        info "Restored old system config via transconf"
    else
        error "Failed to restore $OLD_OVERLAY/upper/$TC_IMAGE, rebooting" || true
        reboot
        false
    fi
fi

# Mark the current boot good
rauc status mark-good >/dev/null

# Delete old overlay to reclaim disk
rm -Rf "$OLD_OVERLAY"

# Don't run this script again
rm "/etc/rcS.d/S30$SCRIPT_NAME"

# Print message at end so that we have some indication in system log
# that everything went well
info "Marked current boot good"
