#!/bin/bash

# The purpose of this script is to sync the CPLD NOFPGA autoload setting with
# values stored in various config files.

NOFPGA_CPLD=/sys/bus/acpi/devices/NIC775D\:00/no_fpga_sw

if [ -f $NOFPGA_CPLD ]; then

# Read the NoFPGAApp.enabled setting from the [SystemSettings] section of
# our main config file.
NOFPGA_INI_VAL=`/usr/local/natinst/bin/nirtcfg --get section=SystemSettings,token=NoFPGAApp.enabled,value="false" | tr "[:upper:]" "[:lower:]"`

# Default to not setting NOFPGA in the CPLD.
NOFPGA_CPLD_VAL=0

# If NoFPGAApp.enabled is 'true' in our config file, set NOFPGA in the CPLD.
case "$NOFPGA_INI_VAL" in
	true)
		NOFPGA_CPLD_VAL=1
		;;
esac

# If we're booting to install mode, set NOFPGA in the CPLD.
BOOT_MODE_INPUT=/tmp/ni_boot_mode_input

if [ -f $BOOT_MODE_INPUT ]; then
	read NEXT_BOOT_MODE < $BOOT_MODE_INPUT
	if [ -n "$NEXT_BOOT_MODE" ]; then
		case "$NEXT_BOOT_MODE" in
		install)
			NOFPGA_CPLD_VAL=1
			;;
		esac
	fi
fi

echo $NOFPGA_CPLD_VAL > $NOFPGA_CPLD

fi
