#!/bin/sh

# This is meant to be sourced from scriptfiles, no shebang
get_set_nilrt_boot()
{
	name=7ab3ae28-52bc-36a8-ff3f-5203fa568c2b-NIOSSharedData
	value=$(efivar -n="$name" -d 2>/dev/null)
	offset=1

	if [ -n "$value" ]; then
		arr_value=($value)
		# get efi variable
		if [ $# -eq 0 ]; then
			value=${arr_value[$offset]}
			echo $value
			return 0
		# set efi variable
		else
			set_efi_variable $1
			return $?
		fi
	fi
	return 1
}

get_set_console_out()
{
	name=5eab87db-1326-4901-9085-8c02b802f878-NIUEFIConsoleOut
	value=$(efivar -n="$name" -d 2>/dev/null)
	offset=0

	if [ -n "$value" ]; then
		arr_value=($value)
		# get efi variable
		if [ $# -eq 0 ]; then
			value=${arr_value[$offset]}
			echo $value
			return 0
		# set efi variable
		else
			set_efi_variable $1
			return $?
		fi
	fi
	return 1
}

set_efi_variable()
{
	arr_value[$offset]=$1
	#currently efivar only writes updated values read from a file
	EFI_VAL_TMP=/tmp/efi_val.$$
	printf '\\x%02x' ${arr_value[@]} | xargs -0 echo -e -n >$EFI_VAL_TMP
	efivar -n="$name" -w -f=$EFI_VAL_TMP
	rm $EFI_VAL_TMP
	return 0
}